# -*- coding: utf-8 -*-
"""Generate CSDL multiple-choice quiz JSON files from lecture content."""
import json
from pathlib import Path

OUT = Path(r"C:\Stuff\Q\Json\nguyen-tac-quan-ly-csdl")
OUT.mkdir(parents=True, exist_ok=True)

MATH = {
    "type": "latex",
    "inline_delimiter": "$",
    "block_delimiter": "$$",
    "renderer_hint": "KaTeX hoặc MathJax",
}


def q(id_, topic, difficulty, pages, question, options, correct, explanation):
    return {
        "id": id_,
        "topic": topic,
        "difficulty": difficulty,
        "source_pages": pages,
        "question": question,
        "options": options,
        "correct_answer": correct,
        "explanation": explanation,
    }


def quiz(chapter_id, title, source_file, questions):
    return {
        "chapter_id": chapter_id,
        "title": title,
        "source_file": source_file,
        "language": "vi",
        "math_format": MATH,
        "question_type": "single_choice",
        "questions": questions,
    }


# ═══════════════════════════════════════════════════════════════════════════
# L01 — Tổng quan về cơ sở dữ liệu
# ═══════════════════════════════════════════════════════════════════════════
L01 = [
    q("csdl-01-001", "Khái niệm dữ liệu và thông tin", "easy", [3],
      "Theo bài giảng, dữ liệu được hiểu là gì?",
      {"A": "Những gì mang lại sự hiểu biết cho con người về hiện tượng, sự vật",
       "B": "Những gì có thật, có thể lưu lại và có ý nghĩa ngầm định",
       "C": "Chỉ là các con số thống kê trên máy tính",
       "D": "Kết quả sau khi con người đã hiểu biết đầy đủ về sự vật"},
      "B", "Dữ liệu là những gì có thật và có thể lưu lại, có ý nghĩa ngầm định. Thông tin mới là thứ mang lại sự hiểu biết cho con người."),
    q("csdl-01-002", "Khái niệm dữ liệu và thông tin", "easy", [3],
      "Thông tin được quản lý trên máy tính thông qua yếu tố nào?",
      {"A": "Các chương trình ứng dụng", "B": "Các dữ liệu", "C": "Hệ điều hành", "D": "Mạng máy tính"},
      "B", "Thông tin được quản lý trên máy tính thông qua các dữ liệu."),
    q("csdl-01-003", "Khái niệm CSDL", "easy", [4],
      "CSDL (Database) là gì?",
      {"A": "Một chương trình phần mềm duy nhất để nhập liệu",
       "B": "Tập hợp các dữ liệu có liên quan với nhau",
       "C": "Chỉ là danh sách tên người dùng hệ thống",
       "D": "Một tập tin Excel bất kỳ"},
      "B", "CSDL là tập hợp các dữ liệu có liên quan với nhau, biểu diễn một phần thế giới thực, được thiết kế với mục đích xác định."),
    q("csdl-01-004", "Khái niệm CSDL", "medium", [4],
      "Tính chất nào sau đây đúng với CSDL theo bài giảng?",
      {"A": "Biểu diễn toàn bộ thế giới thực không giới hạn",
       "B": "Tập hợp dữ liệu lỏng lẻo về logic, không cần mục đích",
       "C": "Biểu diễn một phần thế giới thực; tập hợp dữ liệu chặt chẽ về logic; có mục đích xác định",
       "D": "Chỉ phục vụ một người dùng duy nhất, không chia sẻ"},
      "C", "CSDL biểu diễn một phần thế giới thực, dữ liệu chặt chẽ về logic, được thiết kế với mục đích xác định phục vụ nhóm người và ứng dụng nhất định."),
    q("csdl-01-005", "HQT CSDL", "easy", [5],
      "HQT CSDL (DBMS) là gì?",
      {"A": "Tập hợp các chương trình cho phép tạo và duy trì CSDL trên máy tính",
       "B": "Chỉ là phần cứng lưu trữ dữ liệu",
       "C": "Một loại mạng máy tính",
       "D": "Chỉ là ngôn ngữ lập trình"},
      "A", "HQT CSDL là tập hợp các chương trình cho phép tạo và duy trì cơ sở dữ liệu trên máy tính."),
    q("csdl-01-006", "HQT CSDL", "medium", [5],
      "Chức năng nào không được bài giảng liệt kê trong vai trò của HQT CSDL?",
      {"A": "Định nghĩa kiểu dữ liệu, cấu trúc, ràng buộc",
       "B": "Xử lý: truy vấn, cập nhật, sinh báo cáo",
       "C": "Bảo vệ an toàn hệ thống và bảo mật",
       "D": "Thay thế hoàn toàn hệ điều hành"},
      "D", "HQT CSDL giúp định nghĩa, xây dựng, xử lý, chia sẻ, bảo vệ và duy trì CSDL — không thay thế hệ điều hành."),
    q("csdl-01-007", "Hệ thống xử lý tập tin", "easy", [12],
      "Đặc trưng chính của hệ thống xử lý tập tin là gì?",
      {"A": "Mọi ứng dụng dùng chung một CSDL duy nhất",
       "B": "Tập trung xử lý riêng lẻ; mỗi ứng dụng thiết kế nhiều tập tin dữ liệu riêng",
       "C": "Tự động đảm bảo nhất quán dữ liệu giữa các ứng dụng",
       "D": "Không có dư thừa dữ liệu"},
      "B", "Hệ thống xử lý tập tin tập trung xử lý riêng lẻ; mỗi ứng dụng có nhiều tập tin dữ liệu riêng."),
    q("csdl-01-008", "Hệ thống xử lý tập tin", "easy", [12],
      "Nhược điểm nào sau đây thuộc hệ thống xử lý tập tin?",
      {"A": "Dư thừa và trùng lặp dữ liệu; không nhất quán khi cập nhật",
       "B": "Quá nhiều ràng buộc toàn vẹn",
       "C": "Chỉ hỗ trợ truy vấn SQL",
       "D": "Bắt buộc dùng kiến trúc 3 lược đồ"},
      "A", "Nhược điểm: dư thừa/trùng lặp, không nhất quán, khó truy xuất, cô lập dữ liệu, vấn đề tin cậy, đồng thời và an toàn."),
    q("csdl-01-009", "Đặc điểm CSDL", "medium", [14],
      "Tính tự mô tả của hệ CSDL nghĩa là gì?",
      {"A": "CSDL chỉ chứa dữ liệu, không chứa định nghĩa cấu trúc",
       "B": "Hệ CSDL chứa cả CSDL và định nghĩa đầy đủ về cấu trúc, ràng buộc (siêu dữ liệu trong catalog)",
       "C": "Người dùng phải tự nhớ cấu trúc bảng",
       "D": "Không cần catalog"},
      "B", "Hệ CSDL không chỉ chứa dữ liệu mà còn chứa định nghĩa cấu trúc và ràng buộc, lưu trong catalog (meta-data)."),
    q("csdl-01-010", "Đặc điểm CSDL", "medium", [14, 15],
      "Tính độc lập giữa chương trình và dữ liệu dựa trên điều gì?",
      {"A": "Mọi ứng dụng hard-code cấu trúc tập tin",
       "B": "Cấu trúc CSDL được lưu trong catalog, HQT CSDL che giấu chi tiết lưu trữ",
       "C": "Không dùng mô hình dữ liệu",
       "D": "Chỉ có một người dùng duy nhất"},
      "B", "Cấu trúc lưu trong catalog; trừu tượng hóa dữ liệu che giấu chi tiết lưu trữ → độc lập chương trình–dữ liệu."),
    q("csdl-01-011", "Đặc điểm CSDL", "easy", [15],
      "Cách nhìn (view) trong CSDL là gì?",
      {"A": "Một phần của CSDL hoặc dữ liệu dẫn xuất từ CSDL mà người dùng quan tâm",
       "B": "Toàn bộ bộ nhớ vật lý của máy chủ",
       "C": "Chỉ là giao diện đồ họa của HQT CSDL",
       "D": "Một bản sao offline không liên quan CSDL"},
      "A", "Một cách nhìn là một phần CSDL hoặc dữ liệu được dẫn xuất từ CSDL."),
    q("csdl-01-012", "Người sử dụng CSDL", "easy", [16],
      "Người quản trị CSDL (DBA) có trách nhiệm nào sau đây?",
      {"A": "Chỉ viết mã ứng dụng web",
       "B": "Cấp quyền truy nhập, điều hành giám sát sử dụng, yêu cầu tài nguyên phần cứng/mềm khi cần",
       "C": "Chỉ nhập dữ liệu hàng ngày",
       "D": "Chỉ thiết kế logo hệ thống"},
      "B", "DBA cấp quyền, giám sát sử dụng và yêu cầu tài nguyên khi cần."),
    q("csdl-01-013", "Người sử dụng CSDL", "easy", [16],
      "Người thiết kế CSDL (Database Designer) chịu trách nhiệm chính nào?",
      {"A": "Xác định dữ liệu lưu trữ và chọn cấu trúc biểu diễn/lưu trữ phù hợp",
       "B": "Chỉ vận hành máy chủ 24/7",
       "C": "Chỉ bán phần mềm HQT CSDL",
       "D": "Chỉ gỡ lỗi hệ điều hành"},
      "A", "Database Designer xác định dữ liệu được lưu trữ, chọn cấu trúc thích hợp, liên hệ người dùng để nắm yêu cầu."),
    q("csdl-01-014", "Người sử dụng CSDL", "medium", [17],
      "Người sử dụng thường xuyên thường làm gì?",
      {"A": "Chỉ truy cập CSDL một lần mỗi năm bằng ngôn ngữ truy vấn thô",
       "B": "Truy vấn và cập nhật dữ liệu thường xuyên, dùng các giao tác được đóng gói",
       "C": "Tự cài đặt HQT CSDL mới",
       "D": "Chỉ quản trị quyền truy cập"},
      "B", "Người dùng thường xuyên (ví dụ nhân viên) truy vấn/cập nhật thường xuyên qua giao tác đóng gói."),
    q("csdl-01-015", "Ưu điểm CSDL", "easy", [19],
      "Ưu điểm nào sau đây thuộc hệ CSDL?",
      {"A": "Kiểm soát dư thừa, chia sẻ dữ liệu, sao lưu/phục hồi, ràng buộc toàn vẹn",
       "B": "Buộc mọi ứng dụng tự quản lý tập tin riêng",
       "C": "Loại bỏ hoàn toàn nhu cầu bảo mật",
       "D": "Không cho phép nhiều người dùng"},
      "A", "Ưu điểm gồm kiểm soát dư thừa, chia sẻ, hạn chế truy nhập trái phép, cấu trúc lưu trữ hiệu quả, sao lưu/phục hồi, giao diện, ràng buộc toàn vẹn, v.v."),
    q("csdl-01-016", "Mô hình dữ liệu", "easy", [20],
      "Mô hình dữ liệu là gì?",
      {"A": "Tập hợp các khái niệm mô tả cấu trúc CSDL và các ràng buộc CSDL phải tuân theo",
       "B": "Chỉ là danh sách mật khẩu người dùng",
       "C": "Một thiết bị lưu trữ vật lý",
       "D": "Chỉ là báo cáo Excel"},
      "A", "Mô hình dữ liệu gồm các khái niệm mô tả cấu trúc CSDL và ràng buộc; là phương tiện trừu tượng hóa và giao tiếp."),
    q("csdl-01-017", "Mô hình dữ liệu", "medium", [21],
      "Mô hình mức cao (mức khái niệm) có đặc điểm nào?",
      {"A": "Cung cấp khái niệm gần gũi người dùng (ví dụ ER, đối tượng)",
       "B": "Mô tả chi tiết cách lưu byte trên đĩa",
       "C": "Chỉ dùng cho sao lưu",
       "D": "Không liên quan người dùng"},
      "A", "Mô hình mức cao cung cấp khái niệm gần gũi người dùng: ER, mô hình đối tượng."),
    q("csdl-01-018", "Mô hình dữ liệu", "medium", [21],
      "Mô hình quan hệ và mô hình mạng thuộc nhóm nào?",
      {"A": "Mô hình mức cao thuần túy",
       "B": "Mô hình cài đặt (gần cách tổ chức trên máy tính nhưng người dùng vẫn hiểu được)",
       "C": "Mô hình chỉ dùng cho mạng LAN",
       "D": "Không phải mô hình dữ liệu"},
      "B", "Mô hình cài đặt: quan hệ, mạng — gần cách tổ chức dữ liệu trên máy tính."),
    q("csdl-01-019", "Lược đồ và thể hiện", "easy", [27, 28],
      "Lược đồ CSDL (Database Schema) là gì?",
      {"A": "Dữ liệu tại một thời điểm cụ thể",
       "B": "Các mô tả của CSDL (cấu trúc), biểu diễn bằng sơ đồ lược đồ",
       "C": "Chỉ là bản sao dự phòng",
       "D": "Kết quả của một câu SELECT"},
      "B", "Lược đồ là các mô tả của CSDL; thể hiện (instance) là dữ liệu tại một thời điểm."),
    q("csdl-01-020", "Lược đồ và thể hiện", "easy", [28],
      "Thể hiện CSDL (Database Instance) còn được gọi là gì?",
      {"A": "Trạng thái của CSDL tại một thời điểm xác định",
       "B": "Định nghĩa DDL vĩnh viễn",
       "C": "Catalog rỗng",
       "D": "Chỉ là khóa chính"},
      "A", "Thể hiện là dữ liệu lưu trong CSDL tại một thời điểm — còn gọi là trạng thái CSDL."),
    q("csdl-01-021", "Kiến trúc 3 lược đồ", "easy", [29],
      "Kiến trúc 3 lược đồ gồm những mức nào?",
      {"A": "Mức trong, mức khái niệm, mức ngoài",
       "B": "Chỉ mức trong và mức ngoài",
       "C": "Mức ứng dụng, mức mạng, mức đĩa",
       "D": "Chỉ mức ngoài"},
      "A", "Ba mức: trong (lưu trữ vật lý), khái niệm (cấu trúc cho cộng đồng người dùng), ngoài (phần quan tâm của nhóm người dùng)."),
    q("csdl-01-022", "Kiến trúc 3 lược đồ", "medium", [29],
      "Mục đích của kiến trúc 3 lược đồ gồm?",
      {"A": "Độc lập chương trình–dữ liệu; hỗ trợ nhiều mức nhìn; dùng catalog lưu mô tả CSDL",
       "B": "Loại bỏ hoàn toàn catalog",
       "C": "Chỉ tăng tốc mạng",
       "D": "Chỉ phục vụ một view duy nhất"},
      "A", "Mục đích: độc lập chương trình–dữ liệu, hỗ trợ nhiều mức nhìn, sử dụng catalog."),
    q("csdl-01-023", "Độc lập dữ liệu", "medium", [31],
      "Độc lập logic là gì?",
      {"A": "Thay đổi lược đồ khái niệm mà không phải thay đổi lược đồ ngoài hoặc chương trình ứng dụng",
       "B": "Thay đổi lược đồ trong mà không đổi lược đồ khái niệm",
       "C": "Xóa toàn bộ view khi đổi cột",
       "D": "Chỉ đổi phần cứng"},
      "A", "Độc lập logic: đổi lược đồ khái niệm mà không buộc đổi lược đồ ngoài/chương trình. Độc lập vật lý: đổi lược đồ trong không buộc đổi lược đồ khái niệm."),
    q("csdl-01-024", "Độc lập dữ liệu", "medium", [31],
      "Độc lập vật lý là gì?",
      {"A": "Thay đổi lược đồ trong mà không phải thay đổi lược đồ khái niệm",
       "B": "Thay đổi mọi view khi đổi chỉ mục",
       "C": "Bắt buộc viết lại toàn bộ ứng dụng khi đổi ổ đĩa",
       "D": "Không liên quan lược đồ"},
      "A", "Độc lập vật lý: đổi lược đồ trong (lưu trữ) mà không phải đổi lược đồ khái niệm."),
    q("csdl-01-025", "Ngôn ngữ HQT CSDL", "easy", [32],
      "DDL (Data Definition Language) dùng để làm gì?",
      {"A": "Định nghĩa lược đồ khái niệm (và thường cả trong/ngoài trong thực tế)",
       "B": "Chỉ truy vấn dữ liệu SELECT",
       "C": "Chỉ cấp quyền người dùng",
       "D": "Chỉ sao lưu"},
      "A", "DDL định nghĩa lược đồ khái niệm; hầu hết HQT CSDL dùng DDL cho cả lược đồ trong và ngoài."),
    q("csdl-01-026", "Ngôn ngữ HQT CSDL", "easy", [32],
      "DML (Data Manipulation Language) dùng để làm gì?",
      {"A": "Truy xuất và cập nhật dữ liệu",
       "B": "Chỉ tạo bảng mới",
       "C": "Chỉ định nghĩa view",
       "D": "Chỉ cài đặt HQT CSDL"},
      "A", "DML truy xuất và cập nhật dữ liệu; có DML cấp cao (phi thủ tục) và cấp thấp (thủ tục)."),
    q("csdl-01-027", "Ngôn ngữ HQT CSDL", "medium", [32],
      "VDL (View Definition Language) dùng để định nghĩa gì?",
      {"A": "Các lược đồ ngoài (view)",
       "B": "Chỉ khóa chính",
       "C": "Chỉ phân vùng đĩa",
       "D": "Chỉ trigger"},
      "A", "VDL định nghĩa các lược đồ ngoài."),
    q("csdl-01-028", "Chỉ mục thuật ngữ", "easy", [33],
      "DBMS viết tắt của gì?",
      {"A": "Database Management System — Hệ quản trị CSDL",
       "B": "Data Binary Memory Storage",
       "C": "Digital Backup Main Server",
       "D": "Distributed Business Mail System"},
      "A", "DBMS = Database Management System = Hệ quản trị CSDL."),
    q("csdl-01-029", "Mô hình dữ liệu", "medium", [21, 33],
      "Entity-Relationship (ER) thuộc nhóm mô hình nào?",
      {"A": "Mô hình dữ liệu thực thể liên kết (mức khái niệm/cao)",
       "B": "Mô hình phân cấp thuần vật lý",
       "C": "Chỉ là ngôn ngữ DML",
       "D": "Mô hình mạng bắt buộc"},
      "A", "ER là mô hình thực thể liên kết, dùng ở mức khái niệm."),
    q("csdl-01-030", "Hệ CSDL", "easy", [6],
      "Hệ CSDL (Database System) gồm thành phần nào theo sơ đồ tổng quan?",
      {"A": "CSDL, HQT CSDL, các ứng dụng và người dùng/chương trình truy xuất",
       "B": "Chỉ một tập tin văn bản",
       "C": "Chỉ bộ xử lý CPU",
       "D": "Chỉ trình duyệt web"},
      "A", "Hệ CSDL gồm CSDL, HQT CSDL, ứng dụng, định nghĩa CSDL và xử lý truy vấn/truy xuất dữ liệu."),
    q("csdl-01-031", "Đặc điểm CSDL", "hard", [14, 15],
      "Siêu dữ liệu (meta-data) trong hệ CSDL thường lưu ở đâu?",
      {"A": "Trong catalog của HQT CSDL",
       "B": "Chỉ trong bộ nhớ cache của người dùng",
       "C": "Không được lưu trữ",
       "D": "Chỉ in ra giấy"},
      "A", "Thông tin lưu trong catalog gọi là siêu dữ liệu (meta-data): cấu trúc, kiểu, định dạng, ràng buộc."),
    q("csdl-01-032", "Người sử dụng CSDL", "medium", [18],
      "Người phân tích hệ thống trong nhóm kỹ sư phần mềm làm gì?",
      {"A": "Xác định yêu cầu người dùng và phát triển đặc tả cho giao tác đóng gói",
       "B": "Chỉ thay ổ cứng",
       "C": "Chỉ thiết kế logo",
       "D": "Chỉ viết driver máy in"},
      "A", "Người phân tích hệ thống xác định yêu cầu người dùng (đặc biệt người dùng thường xuyên) và phát triển đặc tả giao tác đóng gói."),
]

# ═══════════════════════════════════════════════════════════════════════════
# L02 — ER
# ═══════════════════════════════════════════════════════════════════════════
L02 = [
    q("csdl-02-001", "Thiết kế CSDL", "easy", [3],
      "Quá trình thiết kế và cài đặt CSDL gồm bao nhiêu giai đoạn theo bài giảng?",
      {"A": "3", "B": "4", "C": "6", "D": "10"},
      "C", "6 giai đoạn: thu thập/phân tích yêu cầu; thiết kế mức khái niệm; lựa chọn HQT CSDL; chuyển đổi mô hình (logic); thiết kế vật lý; cài đặt và tinh chỉnh."),
    q("csdl-02-002", "Thiết kế CSDL", "medium", [3, 4],
      "Thiết kế lược đồ khái niệm có đặc điểm nào?",
      {"A": "Độc lập với HQT CSDL",
       "B": "Phụ thuộc hoàn toàn vào HQT CSDL đã chọn",
       "C": "Chỉ viết câu lệnh DDL",
       "D": "Chỉ thiết kế ứng dụng UI"},
      "A", "Thiết kế lược đồ khái niệm độc lập HQT CSDL; thiết kế logic và trong phụ thuộc HQT CSDL."),
    q("csdl-02-003", "Mô hình ER", "easy", [5],
      "Mô hình ER dùng để làm gì?",
      {"A": "Thiết kế CSDL mức khái niệm; trừu tượng hóa cấu trúc CSDL",
       "B": "Tối ưu chỉ mục vật lý trên đĩa",
       "C": "Chỉ viết trigger",
       "D": "Sao lưu incremental"},
      "A", "ER dùng thiết kế mức khái niệm, trừu tượng hóa cấu trúc CSDL."),
    q("csdl-02-004", "Thực thể và thuộc tính", "easy", [8],
      "Thực thể (Entity) là gì?",
      {"A": "Đối tượng hoặc khái niệm trong thế giới thực",
       "B": "Chỉ là kiểu dữ liệu integer",
       "C": "Một câu lệnh SQL",
       "D": "Chỉ là liên kết giữa hai bảng"},
      "A", "Thực thể là đối tượng/khái niệm thế giới thực (ví dụ nhân viên Nguyễn Văn A, dự án X)."),
    q("csdl-02-005", "Thực thể và thuộc tính", "easy", [8],
      "Thuộc tính (Attribute) là gì?",
      {"A": "Tính chất dùng để mô tả thực thể",
       "B": "Một quan hệ M:N bắt buộc",
       "C": "Chỉ khóa ngoại",
       "D": "Một HQT CSDL"},
      "A", "Thuộc tính mô tả thực thể (tên phòng, giới tính nhân viên...); mỗi thuộc tính có kiểu dữ liệu xác định."),
    q("csdl-02-006", "Loại thuộc tính", "medium", [9],
      "Ví dụ thuộc tính dẫn xuất là gì?",
      {"A": "Tuổi (tính từ ngày sinh)",
       "B": "Mã số nhân viên",
       "C": "Giới tính",
       "D": "Số CMND"},
      "A", "Thuộc tính cơ sở ↔ dẫn xuất: ngày sinh là cơ sở, tuổi là dẫn xuất."),
    q("csdl-02-007", "Loại thuộc tính", "medium", [9],
      "Sở thích của nhân viên thường được mô hình hóa là thuộc tính loại nào?",
      {"A": "Đa trị", "B": "Đơn trị bắt buộc duy nhất", "C": "Khóa chính", "D": "Thực thể yếu"},
      "A", "Mã số nhân viên là đơn trị; sở thích là đa trị."),
    q("csdl-02-008", "Loại thuộc tính", "medium", [9],
      "Họ tên (Họ, Đệm, Tên) là ví dụ của?",
      {"A": "Thuộc tính gộp (composite)",
       "B": "Thuộc tính đơn nguyên tử không tách được",
       "C": "Thực thể yếu",
       "D": "Liên kết tam phân"},
      "A", "Thuộc tính đơn (nguyên tử) ↔ thuộc tính gộp; Họ tên gồm Họ, Đệm, Tên."),
    q("csdl-02-009", "Thuộc tính khóa", "easy", [10],
      "Thuộc tính khóa dùng để làm gì?",
      {"A": "Phân biệt các thực thể cùng kiểu",
       "B": "Chỉ lưu địa chỉ nhà",
       "C": "Chỉ tính tuổi",
       "D": "Loại bỏ mọi liên kết"},
      "A", "Khóa phân biệt các thực thể cùng kiểu; có thể gồm nhiều thuộc tính; một kiểu thực thể có thể có nhiều khóa."),
    q("csdl-02-010", "Liên kết", "easy", [11],
      "Liên kết (Relationship) là gì?",
      {"A": "Sự kết hợp của 2 hoặc nhiều thực thể phân biệt theo một ý nghĩa nào đó",
       "B": "Chỉ một thuộc tính đơn",
       "C": "Một kiểu dữ liệu DATE",
       "D": "Chỉ catalog"},
      "A", "Ví dụ: nhân viên A tham gia dự án X; nhân viên A giám sát nhân viên B."),
    q("csdl-02-011", "Liên kết", "medium", [11],
      "Thuộc tính Giờ của kiểu liên kết THAMGIA giữa NHANVIEN và DUAN cho thấy điều gì?",
      {"A": "Kiểu liên kết có thể có thuộc tính riêng",
       "B": "Liên kết không bao giờ có thuộc tính",
       "C": "Giờ phải là khóa chính của NHANVIEN",
       "D": "DUAN không cần khóa"},
      "A", "Kiểu liên kết có thể có nhiều thuộc tính (ví dụ Giờ của THAMGIA)."),
    q("csdl-02-012", "Bậc liên kết", "easy", [14],
      "Bậc của kiểu liên kết là gì?",
      {"A": "Số lượng kiểu thực thể tham gia vào liên kết",
       "B": "Số byte của thuộc tính",
       "C": "Số khóa ngoại tối đa",
       "D": "Số view trong CSDL"},
      "A", "Bậc = số kiểu thực thể tham gia (nhị phân, tam phân...)."),
    q("csdl-02-013", "Liên kết đệ quy", "medium", [14],
      "Liên kết đệ quy là gì?",
      {"A": "Cùng một kiểu thực thể tham gia liên kết với vai trò khác nhau",
       "B": "Ba kiểu thực thể khác nhau bắt buộc",
       "C": "Chỉ liên kết 1:1 giữa hai phòng ban khác nhau",
       "D": "Không có thực thể tham gia"},
      "A", "Ví dụ: nhân viên A giám sát nhân viên B — cùng kiểu NHANVIEN, vai trò khác nhau."),
    q("csdl-02-014", "Bản số liên kết", "medium", [16, 17],
      "Bản số (min, max) của liên kết mô tả gì?",
      {"A": "Số lượng tối thiểu và tối đa các liên kết mà một thực thể có thể tham gia",
       "B": "Chỉ độ dài chuỗi ký tự",
       "C": "Số cột của bảng",
       "D": "Tốc độ truy vấn"},
      "A", "Lực lượng tối thiểu/tối đa: số liên kết min/max một thực thể có thể tham gia."),
    q("csdl-02-015", "Tỉ lệ lực lượng", "easy", [17],
      "Đối với liên kết nhị phân, ba loại tỉ lệ lực lượng tối đa là?",
      {"A": "1:1, 1:N, M:N",
       "B": "Chỉ 1:1",
       "C": "Chỉ M:N",
       "D": "0:0, 2:2, 3:3"},
      "A", "Ba loại: 1:1, 1:N, M:N."),
    q("csdl-02-016", "Tham gia liên kết", "medium", [17],
      "Ràng buộc tham gia gồm những loại nào?",
      {"A": "Tham gia bắt buộc và tham gia không bắt buộc",
       "B": "Chỉ tham gia bắt buộc",
       "C": "Chỉ tham gia không bắt buộc",
       "D": "Tham gia theo tốc độ mạng"},
      "A", "Lực lượng tối thiểu: tham gia bắt buộc hoặc không bắt buộc."),
    q("csdl-02-017", "Liên kết 1:N", "easy", [18],
      "Liên kết LAMVIEC giữa NHANVIEN và PHONGBAN (một nhân viên một phòng, một phòng nhiều nhân viên) là?",
      {"A": "1:N", "B": "1:1", "C": "M:N", "D": "Tam phân"},
      "A", "Một phòng — nhiều nhân viên; mỗi nhân viên một phòng → 1:N."),
    q("csdl-02-018", "Liên kết M:N", "easy", [20],
      "Liên kết THAMGIA giữa NHANVIEN và DUAN (nhân viên nhiều dự án, dự án nhiều nhân viên) là?",
      {"A": "M:N", "B": "1:1", "C": "1:N bắt buộc một phía", "D": "Không phải liên kết"},
      "A", "THAMGIA là liên kết nhiều–nhiều M:N."),
    q("csdl-02-019", "Thực thể yếu", "easy", [21],
      "Kiểu thực thể yếu (Weak Entity) có đặc điểm nào?",
      {"A": "Phụ thuộc vào một kiểu thực thể khác; có khóa bộ phận",
       "B": "Luôn có khóa chính độc lập hoàn toàn không cần thực thể khác",
       "C": "Không tham gia bất kỳ liên kết nào",
       "D": "Chỉ dùng cho thuộc tính dẫn xuất"},
      "A", "Thực thể yếu phụ thuộc thực thể định danh; khóa bộ phận + khóa thực thể mạnh tạo khóa đầy đủ."),
    q("csdl-02-020", "Thực thể yếu", "medium", [21],
      "Trong ví dụ công ty, THANNHAN thường được mô hình hóa như thế nào?",
      {"A": "Thực thể yếu; NHANVIEN là thực thể định danh; PHUTHUOC là liên kết định danh",
       "B": "Thực thể mạnh độc lập hoàn toàn",
       "C": "Thuộc tính đơn của DUAN",
       "D": "Liên kết tam phân"},
      "A", "THANNHAN yếu, NHANVIEN định danh, PHUTHUOC là identifying relationship."),
    q("csdl-02-021", "ER mở rộng", "medium", [26, 27],
      "Đặc trưng của liên kết cha–con (Is-A) là gì?",
      {"A": "Thực thể lớp con cũng là thực thể lớp cha; kế thừa thuộc tính và liên kết của cha",
       "B": "Lớp con không kế thừa gì từ lớp cha",
       "C": "Lớp cha không thể có thuộc tính",
       "D": "Is-A chỉ dùng cho liên kết M:N"},
      "A", "Một thực thể lớp con cũng là thực thể lớp cha; kế thừa thuộc tính/liên kết; có thể có thuộc tính/liên kết riêng."),
    q("csdl-02-022", "CBH và TQH", "medium", [28, 29],
      "Chuyên biệt hóa (CBH) là quá trình gì?",
      {"A": "Xây dựng các lớp con của một kiểu thực thể",
       "B": "Gộp nhiều kiểu thực thể thành một không có lớp con",
       "C": "Chỉ xóa thuộc tính khóa",
       "D": "Chỉ tạo index"},
      "A", "CBH: xây dựng lớp con; TQH: xây dựng kiểu thực thể tổng quát từ các kiểu đã có."),
    q("csdl-02-023", "CBH và TQH", "medium", [29],
      "Tổng quát hóa (TQH) là quá trình gì?",
      {"A": "Xây dựng một kiểu thực thể tổng quát từ các kiểu thực thể đã có",
       "B": "Chỉ tách thuộc tính đa trị",
       "C": "Chỉ chuyển ER sang SQL",
       "D": "Xóa liên kết đệ quy"},
      "A", "TQH xây dựng kiểu thực thể tổng quát từ các kiểu đã có."),
    q("csdl-02-024", "Ràng buộc CBH/TQH", "hard", [30],
      "Hai loại ràng buộc chính đối với lớp cha–con trong CBH/TQH là?",
      {"A": "Tính tách rời của các lớp con và tính đầy đủ của lớp cha",
       "B": "Chỉ ràng buộc khóa ngoại",
       "C": "Chỉ NOT NULL trên mọi thuộc tính",
       "D": "Chỉ M:N"},
      "A", "Tách rời (disjoint/overlap) và đầy đủ (total/partial); tổ hợp thành 4 trường hợp."),
    q("csdl-02-025", "Kế thừa", "medium", [31],
      "Hai hình thức kế thừa trong CBH/TQH là?",
      {"A": "Kế thừa đơn (phân cấp) và kế thừa bội (dàn)",
       "B": "Chỉ kế thừa đơn",
       "C": "Chỉ kế thừa theo khóa ngoại",
       "D": "Không có kế thừa"},
      "A", "Kế thừa đơn — CBH phân cấp; kế thừa bội — CBH dàn."),
    q("csdl-02-026", "Liên kết tam phân", "medium", [32],
      "Liên kết CUNGCAP giữa NHACUNGCAP, DUAN, VATTU là ví dụ của?",
      {"A": "Liên kết tam phân",
       "B": "Liên kết đệ quy 1 ngôi",
       "C": "Thuộc tính dẫn xuất",
       "D": "Thực thể yếu không liên kết"},
      "A", "Ba kiểu thực thể tham gia → liên kết tam phân; có thể có thuộc tính Soluong."),
    q("csdl-02-027", "Nguyên tắc thiết kế", "easy", [36],
      "Nguyên tắc thiết kế ER nào sau đây đúng?",
      {"A": "Khảo sát quy trình nghiệp vụ; dùng thuật ngữ thế giới thực; chính xác, đơn giản, tránh trùng lắp",
       "B": "Bỏ qua người dùng, chỉ thiết kế theo cảm tính",
       "C": "Luôn gộp mọi thứ vào một thực thể",
       "D": "Không bao giờ dùng khóa"},
      "A", "Khảo sát nghiệp vụ, giao tiếp nhiều nhóm người dùng, thuật ngữ thực tế, chính xác–đơn giản–tránh trùng lắp."),
    q("csdl-02-028", "Tinh chỉnh lược đồ", "hard", [37],
      "Khi nhiều thực thể cùng có thuộc tính Khoa, cách tinh chỉnh hợp lý thường là?",
      {"A": "Tách thành kiểu thực thể KHOA và liên kết tới các thực thể liên quan",
       "B": "Nhân đôi thuộc tính Khoa trên mọi thực thể mà không xem xét ngữ nghĩa",
       "C": "Xóa hết thuộc tính Khoa",
       "D": "Chuyển Khoa thành liên kết tam phân bắt buộc"},
      "A", "Bài giảng minh họa tinh chỉnh: kiểu thực thể hay thuộc tính — tách KHOA thành thực thể."),
    q("csdl-02-029", "Thiết kế mức khái niệm", "medium", [3],
      "Mục đích thiết kế cấu trúc logic và vật lý của CSDL gồm?",
      {"A": "Thỏa mãn yêu cầu thông tin; cấu trúc tự nhiên dễ hiểu; hỗ trợ xử lý hiệu quả",
       "B": "Chỉ giảm dung lượng RAM của máy cá nhân",
       "C": "Chỉ thay thế mạng Internet",
       "D": "Loại bỏ mọi ràng buộc"},
      "A", "Thỏa mãn yêu cầu thông tin người dùng/ứng dụng; cấu trúc tự nhiên dễ hiểu; hỗ trợ xử lý hiệu quả."),
    q("csdl-02-030", "Liên kết mở rộng", "hard", [24],
      "Liên kết mở rộng là gì?",
      {"A": "Liên kết định nghĩa trên ít nhất một liên kết khác",
       "B": "Chỉ liên kết 1:1 giữa hai thực thể mạnh",
       "C": "Thuộc tính đa trị",
       "D": "Khóa bộ phận"},
      "A", "Liên kết mở rộng định nghĩa trên ít nhất một liên kết khác (cung định hướng)."),
    q("csdl-02-031", "Bài toán công ty", "medium", [6, 7],
      "Trong bài toán công ty, một nhân viên làm việc trong bao nhiêu phòng?",
      {"A": "Chỉ một phòng", "B": "Không giới hạn phòng bắt buộc", "C": "Không thuộc phòng nào", "D": "Chỉ thuộc dự án, không thuộc phòng"},
      "A", "Một nhân viên chỉ được làm việc trong một phòng; có thể tham gia nhiều dự án."),
    q("csdl-02-032", "Kiểu thực thể", "easy", [9],
      "Kiểu thực thể (Entity Type) là gì?",
      {"A": "Tập hợp các thực thể có các thuộc tính giống nhau",
       "B": "Một bộ dữ liệu duy nhất",
       "C": "Một câu lệnh DROP",
       "D": "Một chỉ mục B-Tree"},
      "A", "Kiểu thực thể = tập hợp thực thể cùng thuộc tính (tập hợp các nhân viên)."),
]

# ═══════════════════════════════════════════════════════════════════════════
# L03 — Mô hình quan hệ
# ═══════════════════════════════════════════════════════════════════════════
L03 = [
    q("csdl-03-001", "Giới thiệu mô hình quan hệ", "easy", [3],
      "Mô hình dữ liệu quan hệ dùng để thiết kế CSDL ở mức nào?",
      {"A": "Mức logic", "B": "Chỉ mức khái niệm ER", "C": "Chỉ mức vật lý block", "D": "Không dùng cho thiết kế"},
      "A", "Mô hình quan hệ dùng thiết kế mức logic; có cơ sở lý thuyết tập hợp; dùng trong HQT CSDL thương mại."),
    q("csdl-03-002", "Quan hệ", "easy", [4, 5],
      "Trong mô hình quan hệ, dữ liệu được tổ chức như thế nào?",
      {"A": "Thành các bảng hai chiều (table), mỗi bảng là một quan hệ",
       "B": "Chỉ dạng cây phân cấp bắt buộc",
       "C": "Chỉ dạng đồ thị mạng không bảng",
       "D": "Chỉ dạng văn bản tự do"},
      "A", "Dữ liệu tổ chức thành bảng 2 chiều; mỗi bảng là một quan hệ."),
    q("csdl-03-003", "Quan hệ", "easy", [4],
      "Trong quan hệ NHANVIEN, một dòng thường ứng với?",
      {"A": "Một nhân viên (một bộ dữ liệu)",
       "B": "Một thuộc tính của toàn quan hệ",
       "C": "Toàn bộ CSDL",
       "D": "Một khóa ngoại duy nhất"},
      "A", "Dòng ứng với một nhân viên; cột ứng với thuộc tính."),
    q("csdl-03-004", "Thuộc tính", "medium", [6],
      "Trong mô hình quan hệ cơ bản, kiểu dữ liệu phức nào không được áp dụng cho thuộc tính?",
      {"A": "Tập hợp (set), danh sách (list), mảng (array)",
       "B": "Chuỗi ký tự",
       "C": "Số nguyên",
       "D": "Số thực"},
      "A", "Mỗi thuộc tính có kiểu cơ sở (string, integer, real...); set/list/array không được áp dụng."),
    q("csdl-03-005", "Miền xác định", "easy", [7],
      "Miền xác định (Domain) là gì?",
      {"A": "Tập hợp các giá trị nguyên tử gắn với thuộc tính",
       "B": "Tên của HQT CSDL",
       "C": "Một trigger",
       "D": "Một view vật lý"},
      "A", "Domain: tập giá trị nguyên tử; có tên, kiểu, khuôn dạng, mô tả."),
    q("csdl-03-006", "Bộ và lược đồ", "easy", [8],
      "Bộ dữ liệu (tuple) là gì?",
      {"A": "Các dòng của quan hệ (không kể dòng tên thuộc tính)",
       "B": "Tên quan hệ",
       "C": "Danh sách thuộc tính không có giá trị",
       "D": "Catalog toàn cục"},
      "A", "Bộ là các dòng chứa giá trị cụ thể của thuộc tính."),
    q("csdl-03-007", "Bộ và lược đồ", "easy", [8],
      "Lược đồ quan hệ NHANVIEN(MaNV, Ho, Ten, Ngaysinh, Gioitinh) gồm?",
      {"A": "Tên quan hệ và danh sách các thuộc tính",
       "B": "Chỉ các bộ dữ liệu hiện có",
       "C": "Chỉ khóa ngoại",
       "D": "Chỉ index"},
      "A", "Lược đồ quan hệ = tên quan hệ + danh sách thuộc tính."),
    q("csdl-03-008", "Định nghĩa hình thức", "medium", [9],
      "Bậc của lược đồ quan hệ R là gì?",
      {"A": "Số lượng thuộc tính của lược đồ",
       "B": "Số bộ trong trạng thái hiện tại",
       "C": "Số khóa ngoại",
       "D": "Số view"},
      "A", "Bậc của R = số thuộc tính của lược đồ."),
    q("csdl-03-009", "Đặc trưng quan hệ", "medium", [10],
      "Đặc trưng nào đúng với quan hệ?",
      {"A": "Không có các bộ trùng nhau; về toán học không có thứ tự giữa các bộ",
       "B": "Bắt buộc có bộ trùng; thứ tự bộ là một phần định nghĩa toán học",
       "C": "Cho phép thuộc tính đa trị tự do trong 1NF cổ điển",
       "D": "Null bị cấm tuyệt đối trong mọi trường hợp"},
      "A", "Không bộ trùng; thứ tự bộ không quan trọng về mặt toán học; thứ tự giá trị trong bộ quan trọng; null biểu diễn chưa xác định/không áp dụng."),
    q("csdl-03-010", "Ràng buộc toàn vẹn", "easy", [12],
      "Ràng buộc toàn vẹn (RBTV) là gì?",
      {"A": "Các điều kiện mà mọi trạng thái quan hệ phải tuân theo",
       "B": "Chỉ tên bảng",
       "C": "Chỉ kiểu font hiển thị",
       "D": "Một giao thức mạng"},
      "A", "RBTV: điều kiện mọi trạng thái phải tuân; xuất phát từ thế giới thu nhỏ CSDL biểu diễn."),
    q("csdl-03-011", "Siêu khóa và khóa", "medium", [13],
      "Siêu khóa (Super Key) đảm bảo điều gì?",
      {"A": "Tính duy nhất: hai bộ khác nhau không trùng giá trị trên siêu khóa",
       "B": "Mọi thuộc tính đều null",
       "C": "Không có khóa chính",
       "D": "Chỉ có một bộ trong quan hệ"},
      "A", "∀ t1 ≠ t2 ⇒ t1[SK] ≠ t2[SK]. Mọi lược đồ có ít nhất một siêu khóa."),
    q("csdl-03-012", "Siêu khóa và khóa", "medium", [13],
      "Khóa (Key) khác siêu khóa như thế nào?",
      {"A": "Khóa là siêu khóa nhỏ nhất (không có tập con thực sự nào còn là siêu khóa)",
       "B": "Khóa luôn lớn hơn siêu khóa",
       "C": "Khóa không phải siêu khóa",
       "D": "Khóa chỉ gồm toàn bộ thuộc tính bắt buộc"},
      "A", "K là siêu khóa và mọi tập con thực sự của K không là siêu khóa → khóa là siêu khóa tối thiểu."),
    q("csdl-03-013", "Khóa chính", "easy", [13],
      "Khi một lược đồ có nhiều khóa chỉ định (candidate key), người ta thường?",
      {"A": "Chọn một trong số đó làm khóa chính (primary key)",
       "B": "Bỏ hết các khóa",
       "C": "Dùng tất cả làm foreign key bắt buộc",
       "D": "Chỉ giữ khóa dài nhất"},
      "A", "Có thể có nhiều candidate key; chọn một làm primary key; thuộc tính khóa được gạch dưới."),
    q("csdl-03-014", "CSDL quan hệ", "medium", [15],
      "Lược đồ CSDL quan hệ gồm?",
      {"A": "Tập các lược đồ quan hệ S và tập RBTV IC",
       "B": "Chỉ một bảng duy nhất không ràng buộc",
       "C": "Chỉ dữ liệu instance",
       "D": "Chỉ mật khẩu DBA"},
      "A", "S = {R1,...,Rm} + IC; trạng thái hợp lệ nếu thỏa mọi RBTV."),
    q("csdl-03-015", "RBTV thực thể", "easy", [17],
      "RBTV thực thể quy định gì?",
      {"A": "Giá trị khóa chính không thể là giá trị rỗng (null)",
       "B": "Khóa ngoại luôn null",
       "C": "Mọi thuộc tính phải null",
       "D": "Không có khóa chính"},
      "A", "Entity integrity: khóa chính không null; xác định trên từng quan hệ."),
    q("csdl-03-016", "RBTV tham chiếu", "easy", [17, 18],
      "RBTV tham chiếu yêu cầu gì?",
      {"A": "Bộ được tham chiếu trong quan hệ đích phải tồn tại trước",
       "B": "Khóa ngoại luôn trỏ tới bộ không tồn tại",
       "C": "Chỉ áp dụng trong một quan hệ duy nhất, không bao giờ giữa hai quan hệ",
       "D": "Xóa catalog"},
      "A", "Nếu bộ R tham chiếu bộ S thì bộ S phải tồn tại; xác định giữa hai quan hệ (hoặc tự tham chiếu)."),
    q("csdl-03-017", "Khóa ngoại", "medium", [18],
      "Khóa ngoại FK của R1 tham chiếu R2 cần thỏa điều nào?",
      {"A": "FK cùng miền với PK của R2; mọi t1[FK] phải bằng t2[PK] của một bộ tồn tại trong R2",
       "B": "FK khác miền hoàn toàn với PK",
       "C": "FK không liên quan PK",
       "D": "FK luôn là siêu khóa của R2"},
      "A", "Hai điều kiện domain khớp và mọi giá trị FK phải khớp một PK tồn tại."),
    q("csdl-03-018", "Khóa ngoại", "hard", [18],
      "Nhận xét nào đúng về khóa ngoại?",
      {"A": "Khóa ngoại có thể tham chiếu khóa chính trong cùng lược đồ (tự tham chiếu)",
       "B": "Một thuộc tính không thể vừa thuộc PK vừa thuộc FK",
       "C": "Chỉ được có đúng một RBTV tham chiếu trong cả CSDL",
       "D": "Không thể có nhiều FK trỏ cùng một PK"},
      "A", "FK có thể tự tham chiếu; một thuộc tính có thể vừa PK vừa FK; có thể nhiều FK tới cùng PK."),
    q("csdl-03-019", "Chuyển ER→quan hệ", "easy", [21],
      "Chuyển kiểu thực thể mạnh sang quan hệ thường tạo ra?",
      {"A": "Một quan hệ với các thuộc tính đơn (sau khi bung thuộc tính gộp) và khóa của thực thể",
       "B": "Không tạo quan hệ nào",
       "C": "Chỉ tạo view",
       "D": "Chỉ tạo domain"},
      "A", "Thực thể mạnh → quan hệ với thuộc tính và khóa tương ứng."),
    q("csdl-03-020", "Chuyển ER→quan hệ", "medium", [22],
      "Khi chuyển thực thể yếu THANNHAN, khóa của quan hệ thường gồm?",
      {"A": "Khóa của thực thể mạnh (MaNV) kết hợp khóa bộ phận (Ten)",
       "B": "Chỉ Ten, không cần MaNV",
       "C": "Chỉ Gioitinh",
       "D": "Không có khóa"},
      "A", "Thực thể yếu: đưa khóa thực thể định danh vào quan hệ yếu + khóa bộ phận."),
    q("csdl-03-021", "Chuyển liên kết 1:N", "medium", [28],
      "Chuyển liên kết 1:N LAMVIEC (N phía NHANVIEN) thường làm gì?",
      {"A": "Thêm khóa của PHONGBAN (MaPB) vào quan hệ NHANVIEN như khóa ngoại",
       "B": "Tạo bảng riêng chỉ chứa MaNV",
       "C": "Xóa NHANVIEN",
       "D": "Thêm mọi thuộc tính NHANVIEN vào PHONGBAN bắt buộc"},
      "A", "1:N: đưa khóa phía 1 sang phía N làm FK."),
    q("csdl-03-022", "Chuyển liên kết M:N", "medium", [29],
      "Chuyển liên kết M:N THAMGIA thường tạo ra?",
      {"A": "Quan hệ mới có khóa gồm khóa hai phía (MaNV, MaDA) và thuộc tính của liên kết (SoGio)",
       "B": "Chỉ thêm MaDA vào NHANVIEN",
       "C": "Chỉ thêm MaNV vào DUAN",
       "D": "Không cần quan hệ mới"},
      "A", "M:N → quan hệ riêng chứa hai khóa + thuộc tính liên kết."),
    q("csdl-03-023", "Chuyển thuộc tính đa trị", "medium", [30],
      "Thuộc tính đa trị Truso của PHONGBAN được chuyển bằng cách?",
      {"A": "Tạo quan hệ riêng TRUSO_PHONG(Truso, MaPB)",
       "B": "Giữ nguyên một cột chứa danh sách trong PHONGBAN (theo mô hình quan hệ chuẩn)",
       "C": "Xóa thuộc tính đa trị",
       "D": "Chuyển thành khóa chính duy nhất của PHONGBAN"},
      "A", "Thuộc tính đa trị → quan hệ riêng gồm thuộc tính đa trị + khóa thực thể sở hữu."),
    q("csdl-03-024", "Chuyển liên kết 1:1", "hard", [24, 25],
      "Một cách chuyển liên kết 1:1 QUANLY giữa NHANVIEN và PHONGBAN là?",
      {"A": "Đưa khóa MaNV vào PHONGBAN làm TrPhong (FK) cùng thuộc tính NgayNhChuc",
       "B": "Luôn tạo 3 quan hệ trung gian bắt buộc",
       "C": "Không thể biểu diễn 1:1 trong mô hình quan hệ",
       "D": "Chỉ dùng thuộc tính đa trị"},
      "A", "1:1: có thể đưa khóa một phía sang phía kia; ví dụ TrPhong trong PHONGBAN."),
    q("csdl-03-025", "Chuyển liên kết bậc cao", "medium", [31],
      "Chuyển liên kết tam phân CUNGCAP thường tạo?",
      {"A": "Quan hệ CUNGCAP với khóa gồm các khóa của ba thực thể (+ thuộc tính Soluong)",
       "B": "Chỉ một cột trong NHACUNGCAP",
       "C": "Không cần quan hệ",
       "D": "Chỉ domain"},
      "A", "Liên kết bậc cao → quan hệ chứa khóa các phía tham gia + thuộc tính liên kết."),
    q("csdl-03-026", "Chuyển EER", "medium", [32],
      "Một cách chuyển chuyên biệt hóa NHANVIEN với các lớp con là?",
      {"A": "Giữ quan hệ NHANVIEN và tạo quan hệ lớp con có MaNV làm PK/FK",
       "B": "Xóa lớp cha hoàn toàn luôn luôn",
       "C": "Gộp mọi lớp con thành một thuộc tính đa trị duy nhất bắt buộc",
       "D": "Không chuyển được CBH sang quan hệ"},
      "A", "Ví dụ: NHANVIEN + BANHANG/KYTHUAT/KYSUPHANMEM với MaNV liên kết."),
    q("csdl-03-027", "Ký hiệu", "easy", [11],
      "Ký hiệu t[Ai] hoặc t.Ai nghĩa là gì?",
      {"A": "Giá trị của thuộc tính Ai trong bộ t",
       "B": "Tên lược đồ",
       "C": "Số bộ của quan hệ",
       "D": "Miền xác định của Ai"},
      "A", "t[Ai], t.Ai là giá trị thuộc tính Ai trong bộ t."),
    q("csdl-03-028", "Đặc trưng quan hệ", "medium", [10],
      "Giá trị null trong bộ dùng để biểu diễn?",
      {"A": "Giá trị chưa xác định hoặc không thể áp dụng",
       "B": "Luôn bằng 0",
       "C": "Luôn bằng chuỗi rỗng bắt buộc",
       "D": "Khóa chính"},
      "A", "Null: chưa xác định hoặc không áp dụng cho thuộc tính."),
    q("csdl-03-029", "Ràng buộc mô hình", "easy", [12],
      "Ba loại RBTV chính theo bài giảng mô hình quan hệ là?",
      {"A": "Dựa trên bản chất mô hình; dựa trên lược đồ; dựa trên ứng dụng",
       "B": "Chỉ dựa trên ứng dụng",
       "C": "Chỉ dựa trên phần cứng",
       "D": "Chỉ dựa trên giao diện"},
      "A", "Ba loại: bản chất mô hình, lược đồ, ứng dụng."),
    q("csdl-03-030", "Trạng thái hợp lệ", "medium", [15],
      "Trạng thái CSDL được gọi là hợp lệ khi nào?",
      {"A": "Khi thỏa mọi RBTV trong IC",
       "B": "Khi có ít nhất một null",
       "C": "Khi không có khóa chính",
       "D": "Khi chỉ có một bảng"},
      "A", "Trạng thái hợp lệ nếu thỏa mọi RBTV."),
    q("csdl-03-031", "Chuyển 1:1 trường hợp đặc biệt", "hard", [26],
      "Khi liên kết 1:1 và cả hai phía tham gia bắt buộc, một phương án là?",
      {"A": "Gộp hai thực thể vào một quan hệ (ví dụ CLB_SVD)",
       "B": "Luôn dùng thuộc tính đa trị",
       "C": "Không biểu diễn được",
       "D": "Chỉ dùng chia quan hệ"},
      "A", "Ví dụ CLB–SVD sở hữu 1:1 có thể gộp thành CLB_SVD."),
    q("csdl-03-032", "Quan hệ", "easy", [5],
      "Quan hệ có thể chứa dữ liệu của?",
      {"A": "Một tập thực thể hoặc một tập liên kết",
       "B": "Chỉ tập thực thể, không bao giờ liên kết",
       "C": "Chỉ meta-data catalog",
       "D": "Chỉ log hệ thống"},
      "A", "Quan hệ chứa dữ liệu tập thực thể hoặc tập liên kết."),
]

# ═══════════════════════════════════════════════════════════════════════════
# L04 — Đại số quan hệ
# ═══════════════════════════════════════════════════════════════════════════
L04 = [
    q("csdl-04-001", "Giới thiệu", "easy", [3],
      "Đại số quan hệ là gì?",
      {"A": "Tập hợp các phép toán cơ sở của mô hình dữ liệu quan hệ",
       "B": "Một ngôn ngữ lập trình hướng đối tượng",
       "C": "Chỉ là giao diện GUI",
       "D": "Một hệ thống tệp"},
      "A", "Đại số quan hệ: tập phép toán cơ sở; biểu thức là chuỗi phép toán; kết quả là thể hiện quan hệ."),
    q("csdl-04-002", "Giới thiệu", "medium", [3],
      "Ý nghĩa của đại số quan hệ gồm?",
      {"A": "Cơ sở hình thức cho phép toán mô hình quan hệ; cơ sở cài đặt và tối ưu truy vấn; áp dụng trong SQL",
       "B": "Chỉ dùng để vẽ ER",
       "C": "Thay thế hoàn toàn hệ điều hành",
       "D": "Chỉ định nghĩa trigger"},
      "A", "Cơ sở hình thức, cài đặt/tối ưu truy vấn, áp dụng trong SQL."),
    q("csdl-04-003", "Phép chọn", "easy", [6],
      "Phép chọn σ_ĐK(R) dùng để làm gì?",
      {"A": "Rút trích các bộ thỏa điều kiện chọn từ một quan hệ",
       "B": "Rút trích các cột theo danh sách thuộc tính",
       "C": "Gộp hai quan hệ theo khóa",
       "D": "Đổi tên quan hệ"},
      "A", "Phép chọn rút các bộ thỏa ĐK."),
    q("csdl-04-004", "Phép chọn", "medium", [7],
      "Đặc trưng nào đúng với phép chọn?",
      {"A": "Có tính giao hoán; kết quả cùng bậc với R; số bộ ≤ số bộ R",
       "B": "Không giao hoán; bậc luôn giảm",
       "C": "Luôn tăng số bộ",
       "D": "Đổi tên thuộc tính bắt buộc"},
      "A", "σ có giao hoán; cùng bậc; số bộ ≤ R."),
    q("csdl-04-005", "Phép chiếu", "easy", [8],
      "Phép chiếu π_DSTT(R) dùng để làm gì?",
      {"A": "Rút trích các cột ứng với các thuộc tính được chỉ định",
       "B": "Lọc dòng theo điều kiện logic",
       "C": "Tính Cartesian",
       "D": "Chia quan hệ"},
      "A", "Chiếu rút các cột theo danh sách thuộc tính."),
    q("csdl-04-006", "Phép chiếu", "medium", [9],
      "Đặc trưng nào đúng với phép chiếu?",
      {"A": "Không giao hoán; loại bỏ bộ trùng; bậc bằng số thuộc tính trong danh sách",
       "B": "Luôn giao hoán tuyệt đối",
       "C": "Không bao giờ loại trùng",
       "D": "Bậc luôn bằng bậc R"},
      "A", "π không giao hoán, loại trùng, bậc = |DSTT|."),
    q("csdl-04-007", "Phép đổi tên", "easy", [11],
      "Phép đổi tên ρ dùng để?",
      {"A": "Đổi tên quan hệ và/hoặc các thuộc tính",
       "B": "Xóa bộ",
       "C": "Tạo khóa chính",
       "D": "Tính tổng"},
      "A", "ρS(R), ρS(B1..Bn)(R), ρ(B1..Bn)(R)..."),
    q("csdl-04-008", "Phép gán", "easy", [10],
      "Phép gán R' ← E dùng để?",
      {"A": "Lưu kết quả biểu thức đại số quan hệ vào tên quan hệ tạm, đơn giản hóa chuỗi phép toán",
       "B": "Xóa quan hệ R",
       "C": "Tạo RBTV",
       "D": "Chỉ đổi font"},
      "A", "Gán lưu kết quả E vào R' để đơn giản hóa biểu thức phức tạp."),
    q("csdl-04-009", "Khả hợp", "medium", [14],
      "Hai quan hệ R và S khả hợp khi nào?",
      {"A": "Cùng bậc và miền giá trị tương ứng từng thuộc tính tương thích",
       "B": "Chỉ cùng tên quan hệ",
       "C": "Chỉ cùng số bộ",
       "D": "Không cần điều kiện"},
      "A", "Bậc R = bậc S và domain Ai ≡ Bi."),
    q("csdl-04-010", "Phép hội", "easy", [15],
      "R ∪ S gồm các bộ nào?",
      {"A": "Các bộ thuộc R hoặc thuộc S (loại trùng)",
       "B": "Chỉ các bộ thuộc cả R và S",
       "C": "Chỉ các bộ thuộc R không thuộc S",
       "D": "Tích mọi cặp bộ"},
      "A", "Hội: t ∈ R ∨ t ∈ S; trùng bị loại."),
    q("csdl-04-011", "Phép giao", "easy", [16],
      "R ∩ S gồm các bộ nào?",
      {"A": "Các bộ thuộc R đồng thời thuộc S",
       "B": "Mọi bộ của R",
       "C": "Mọi bộ của S không thuộc R",
       "D": "Cartesian"},
      "A", "Giao: t ∈ R ∧ t ∈ S."),
    q("csdl-04-012", "Phép hiệu", "easy", [17],
      "R − S gồm các bộ nào?",
      {"A": "Các bộ thuộc R nhưng không thuộc S",
       "B": "Các bộ thuộc S nhưng không thuộc R",
       "C": "Hội R và S",
       "D": "Giao R và S"},
      "A", "Hiệu: t ∈ R ∧ t ∉ S."),
    q("csdl-04-013", "Phép tập hợp", "medium", [18],
      "Phép nào có tính giao hoán?",
      {"A": "Hội và giao",
       "B": "Chỉ hiệu",
       "C": "Chỉ chia",
       "D": "Không phép nào"},
      "A", "∪ và ∩ giao hoán và kết hợp; hiệu không giao hoán."),
    q("csdl-04-014", "Tích Cartesian", "medium", [19],
      "Đặc điểm của R × S là gì?",
      {"A": "Mỗi bộ là tổ hợp một bộ R và một bộ S; bậc = bậc R + bậc S; số bộ = |R|×|S|",
       "B": "Cùng bậc với R",
       "C": "Số bộ = |R| + |S|",
       "D": "Bắt buộc R và S khả hợp"},
      "A", "Cartesian: tổ hợp mọi cặp; bậc cộng; số bộ nhân; không yêu cầu khả hợp."),
    q("csdl-04-015", "Phép kết", "easy", [21],
      "Phép kết dùng để?",
      {"A": "Kết hợp các bộ có liên quan từ hai quan hệ",
       "B": "Chỉ chiếu một cột",
       "C": "Chỉ đổi tên",
       "D": "Chỉ đếm bộ"},
      "A", "Join kết hợp bộ liên quan; có theta, equi, natural."),
    q("csdl-04-016", "Kết bằng", "medium", [23],
      "Kết bằng (Equi Join) là gì?",
      {"A": "Kết theta trong đó mọi toán tử so sánh trong điều kiện đều là =",
       "B": "Kết chỉ dùng <",
       "C": "Không phải phép kết",
       "D": "Chỉ outer join"},
      "A", "Equi join: điều kiện toàn dấu =."),
    q("csdl-04-017", "Kết tự nhiên", "medium", [24],
      "Kết tự nhiên (Natural Join) yêu cầu gì?",
      {"A": "Kết bằng trên các cặp thuộc tính cùng tên (và cùng miền); gộp các cột trùng tên",
       "B": "Luôn giữ mọi cặp cột trùng giá trị khác tên mà không đổi tên",
       "C": "Không cần điều kiện",
       "D": "Chỉ dùng trên một quan hệ"},
      "A", "Natural join: equi trên thuộc tính cùng tên/cùng miền; nếu khác tên cần rename trước."),
    q("csdl-04-018", "Phép chia", "hard", [25],
      "Phép chia R ÷ S dùng khi nào?",
      {"A": "Rút các bộ của R liên quan với tất cả các bộ của S",
       "B": "Tính tổng số học",
       "C": "Chỉ lọc null",
       "D": "Đổi tên thuộc tính"},
      "A", "Division: T(Y) = {t | t ∈ π_Y(R) ∧ ∀u∈S (t,u)∈R}, Y = Z−X."),
    q("csdl-04-019", "Ví dụ truy vấn", "medium", [27],
      "Tìm nhân viên tham gia tất cả dự án do phòng 5 điều phối thường dùng phép nào?",
      {"A": "Phép chia (sau khi chiếu MaNV, MaDA và tập MaDA phòng 5)",
       "B": "Chỉ phép chọn đơn giản một điều kiện",
       "C": "Chỉ đổi tên",
       "D": "Chỉ hiệu không chiếu"},
      "A", "Bài giảng: Q2 ÷ Q1 với Q1 = dự án phòng 5, Q2 = tham gia."),
    q("csdl-04-020", "Hàm tập hợp", "easy", [29],
      "Các hàm tập hợp cơ bản trong đại số mở rộng gồm?",
      {"A": "SUM, AVG, MAX, MIN, COUNT",
       "B": "Chỉ UNION",
       "C": "Chỉ RENAME",
       "D": "Chỉ DIVIDE"},
      "A", "SUM, AVG, MAX, MIN, COUNT; gom nhóm bằng ℱ."),
    q("csdl-04-021", "Kết mở rộng", "medium", [31],
      "Phép kết mở rộng (outer join) nhằm mục đích gì?",
      {"A": "Giữ lại các bộ không khớp để tránh mất thông tin / phục vụ báo cáo",
       "B": "Luôn xóa bộ không khớp",
       "C": "Chỉ tăng tốc index",
       "D": "Thay thế phép chiếu"},
      "A", "Outer join giữ bộ không liên kết được (trái/phải/hai phía)."),
    q("csdl-04-022", "Kết mở rộng trái", "medium", [32],
      "Left outer join giữ lại?",
      {"A": "Tất cả bộ của quan hệ bên trái, kể cả không khớp bên phải (phần thiếu = null)",
       "B": "Chỉ bộ khớp",
       "C": "Chỉ bộ bên phải",
       "D": "Không giữ bộ nào"},
      "A", "Left outer join giữ mọi bộ bên trái."),
    q("csdl-04-023", "Phép toán 1 ngôi", "easy", [5],
      "Các phép toán một ngôi gồm?",
      {"A": "Chọn, chiếu, đổi tên",
       "B": "Hội, giao, hiệu",
       "C": "Kết, chia",
       "D": "Chỉ Cartesian"},
      "A", "1 ngôi: select, project, rename."),
    q("csdl-04-024", "Phép toán 2 ngôi", "easy", [13],
      "Phép toán tập hợp hai ngôi gồm?",
      {"A": "Hội, giao, hiệu, tích Cartesian",
       "B": "Chỉ chọn và chiếu",
       "C": "Chỉ đổi tên",
       "D": "Chỉ gom nhóm"},
      "A", "Tập hợp: ∪, ∩, −, ×; phi tập hợp: join, division."),
    q("csdl-04-025", "Chuỗi phép toán", "medium", [10, 12],
      "Biểu thức π_Ho,Ten,Gtinh,Luong(σ_MaPB=5(NHANVIEN)) nghĩa là?",
      {"A": "Chọn nhân viên phòng 5 rồi chiếu các thuộc tính họ, tên, giới tính, lương",
       "B": "Chỉ hội hai quan hệ",
       "C": "Chia NHANVIEN cho phòng 5",
       "D": "Đổi tên phòng 5"},
      "A", "Chọn trước (hoặc lồng), rồi chiếu các cột cần lấy."),
    q("csdl-04-026", "Theta join", "medium", [22],
      "Trong kết theta, điều kiện so sánh nối thuộc tính hai quan hệ dùng toán tử?",
      {"A": "=, <, ≤, >, ≥, ≠ (và kết hợp bằng ∧)",
       "B": "Chỉ OR giữa quan hệ",
       "C": "Chỉ LIKE",
       "D": "Không có điều kiện"},
      "A", "Theta join: Ai θ Bj với θ là toán tử so sánh."),
    q("csdl-04-027", "Mở rộng chiếu", "hard", [9],
      "Mở rộng phép chiếu cho phép?",
      {"A": "Dùng phép toán số học trong danh sách thuộc tính (ví dụ π_A,2*C(R))",
       "B": "Chỉ đổi tên bắt buộc",
       "C": "Chỉ Cartesian",
       "D": "Xóa quan hệ"},
      "A", "Extended projection cho phép biểu thức số học trên thuộc tính."),
    q("csdl-04-028", "Toán hạng", "easy", [4],
      "Toán hạng của đại số quan hệ là gì?",
      {"A": "Các thể hiện quan hệ (và tập hợp)",
       "B": "Chỉ số nguyên",
       "C": "Chỉ chuỗi SQL thô không quan hệ",
       "D": "Chỉ file hệ thống"},
      "A", "Toán hạng: thể hiện quan hệ, tập hợp."),
    q("csdl-04-029", "Full outer join", "medium", [34],
      "Full outer join giữ lại?",
      {"A": "Các bộ không khớp ở cả hai phía",
       "B": "Chỉ bên trái",
       "C": "Chỉ bộ trùng khóa chính",
       "D": "Không giữ bộ không khớp"},
      "A", "Full outer join giữ bộ không khớp hai phía."),
    q("csdl-04-030", "Gom nhóm", "medium", [29],
      "Cú pháp <DSTT> ℱ <DSH>(R) dùng để?",
      {"A": "Gom nhóm theo thuộc tính rồi áp dụng hàm tập hợp trên từng nhóm",
       "B": "Chỉ đổi tên",
       "C": "Chỉ hiệu",
       "D": "Chỉ chia"},
      "A", "Grouping + aggregate functions."),
    q("csdl-04-031", "Ví dụ hội", "medium", [20],
      "Tìm mã NV phòng 5 hoặc giám sát NV phòng 5 thường dùng?",
      {"A": "Chiếu MaNV và MaGS từ các NV phòng 5 rồi lấy hội",
       "B": "Chỉ giao hai tập rỗng",
       "C": "Chỉ natural join với chính nó không chọn",
       "D": "Chỉ outer join phải"},
      "A", "Q2 ∪ Q3 với Q2=π_MaNV, Q3=π_MaGS từ σ_MaPB=5."),
    q("csdl-04-032", "Phép chọn điều kiện", "easy", [7],
      "Điều kiện trong phép chọn được nối bởi toán tử logic nào?",
      {"A": "∧, ∨, ¬",
       "B": "Chỉ ×",
       "C": "Chỉ ÷",
       "D": "Chỉ ∪"},
      "A", "Mệnh đề nối bởi AND/OR/NOT (∧,∨,¬)."),
]

# ═══════════════════════════════════════════════════════════════════════════
# L05 — SQL
# ═══════════════════════════════════════════════════════════════════════════
L05 = [
    q("csdl-05-001", "Giới thiệu SQL", "easy", [3],
      "SQL là viết tắt của?",
      {"A": "Structured Query Language",
       "B": "Simple Queue Logic",
       "C": "System Quick Loader",
       "D": "Sequential Query List"},
      "A", "SQL = Structured Query Language; ngôn ngữ cấp cao; chuẩn hóa ANSI/ISO."),
    q("csdl-05-002", "Giới thiệu SQL", "easy", [3],
      "SQL được phát triển ban đầu bởi?",
      {"A": "IBM (những năm 1970)",
       "B": "Microsoft năm 2010",
       "C": "Oracle năm 1999 duy nhất",
       "D": "Google"},
      "A", "Phát triển bởi IBM khoảng 1970; các chuẩn SQL-86, SQL-92, SQL-99..."),
    q("csdl-05-003", "Định nghĩa dữ liệu", "easy", [4],
      "Các lệnh định nghĩa dữ liệu gồm?",
      {"A": "CREATE/DROP DATABASE, CREATE/DROP/ALTER TABLE, CREATE/DROP DOMAIN",
       "B": "Chỉ SELECT",
       "C": "Chỉ INSERT",
       "D": "Chỉ GRANT"},
      "A", "DDL: CREATE/DROP DATABASE, TABLE, DOMAIN; ALTER TABLE."),
    q("csdl-05-004", "Kiểu dữ liệu", "easy", [5],
      "DECIMAL(p,n) thuộc nhóm kiểu nào?",
      {"A": "Số thập phân",
       "B": "Chuỗi unicode",
       "C": "Bit",
       "D": "Timestamp"},
      "A", "Số thập phân: DECIMAL(p,n); số nguyên INT/SMALLINT; số thực FLOAT/REAL/DOUBLE."),
    q("csdl-05-005", "Kiểu dữ liệu", "easy", [6],
      "VARCHAR(n) là gì?",
      {"A": "Chuỗi ký tự độ dài thay đổi tối đa n",
       "B": "Số nguyên n bit",
       "C": "Ngày giờ",
       "D": "Bit cố định"},
      "A", "CHARACTER VARYING(n) / VARCHAR(n): chuỗi độ dài thay đổi."),
    q("csdl-05-006", "Tạo bảng", "medium", [8],
      "Trong CREATE TABLE, RBTV có thể gồm?",
      {"A": "NOT NULL, UNIQUE, DEFAULT, PRIMARY KEY, FOREIGN KEY, CHECK",
       "B": "Chỉ SELECT",
       "C": "Chỉ ORDER BY",
       "D": "Chỉ GROUP BY"},
      "A", "Các ràng buộc cột/bảng: NOT NULL, NULL, UNIQUE, DEFAULT, PK, FK, CHECK."),
    q("csdl-05-007", "Đặt tên RBTV", "easy", [10],
      "Cú pháp đặt tên ràng buộc là?",
      {"A": "CONSTRAINT <tên> <RBTV>",
       "B": "NAME <tên> ONLY",
       "C": "INDEX <tên>",
       "D": "ALIAS <tên>"},
      "A", "CONSTRAINT <tên RBTV> <RBTV>."),
    q("csdl-05-008", "Sửa bảng", "easy", [12],
      "Thêm cột vào bảng dùng lệnh nào?",
      {"A": "ALTER TABLE ... ADD COLUMN ...",
       "B": "INSERT COLUMN",
       "C": "UPDATE COLUMN ADD",
       "D": "CREATE COLUMN"},
      "A", "ALTER TABLE <bảng> ADD COLUMN <tên> <kiểu>."),
    q("csdl-05-009", "Cập nhật dữ liệu", "easy", [15],
      "Chèn một dòng vào bảng dùng?",
      {"A": "INSERT INTO ... VALUES (...)",
       "B": "ADD ROW",
       "C": "PUT INTO",
       "D": "APPEND TABLE"},
      "A", "INSERT INTO <bảng> [(ds tt)] VALUES (ds giá trị)."),
    q("csdl-05-010", "Cập nhật dữ liệu", "easy", [16],
      "Xóa các nhân viên phòng 5 dùng?",
      {"A": "DELETE FROM NHANVIEN WHERE MaPhong = 5",
       "B": "REMOVE NHANVIEN 5",
       "C": "DROP ROW NHANVIEN",
       "D": "ERASE FROM NHANVIEN"},
      "A", "DELETE FROM <bảng> [WHERE <đk>]."),
    q("csdl-05-011", "Cập nhật dữ liệu", "easy", [18],
      "Tăng lương tất cả nhân viên 10% dùng?",
      {"A": "UPDATE NHANVIEN SET Luong = 1.1 * Luong",
       "B": "MODIFY Luong * 1.1",
       "C": "ALTER Luong INCREASE 10%",
       "D": "SET ALL Luong + 10%"},
      "A", "UPDATE ... SET ... [WHERE ...]."),
    q("csdl-05-012", "Truy vấn", "easy", [19],
      "Thứ tự các mệnh đề trong SELECT đầy đủ theo bài giảng là?",
      {"A": "SELECT ... FROM ... [WHERE] [GROUP BY] [HAVING] [ORDER BY]",
       "B": "WHERE ... SELECT ... FROM",
       "C": "GROUP BY ... SELECT ... HAVING ... FROM",
       "D": "ORDER BY ... FROM ... SELECT"},
      "A", "SELECT dstt FROM dsb [WHERE] [GROUP BY] [HAVING] [ORDER BY]."),
    q("csdl-05-013", "Ánh xạ đại số–SQL", "medium", [20],
      "π_dstt(R) tương ứng SQL nào?",
      {"A": "SELECT dstt FROM R",
       "B": "SELECT * FROM R WHERE dstt",
       "C": "DELETE dstt FROM R",
       "D": "UPDATE R SET dstt"},
      "A", "Chiếu ↔ SELECT dstt FROM R; chọn ↔ WHERE; tích ↔ FROM R,S."),
    q("csdl-05-014", "Phép tập hợp SQL", "medium", [22],
      "UNION không có ALL có đặc điểm gì?",
      {"A": "Loại các dòng giống nhau trong kết quả",
       "B": "Giữ mọi dòng trùng",
       "C": "Không yêu cầu khả hợp",
       "D": "Chỉ dùng với ORDER BY bắt buộc"},
      "A", "UNION/EXCEPT/INTERSECT loại trùng; thêm ALL để giữ trùng."),
    q("csdl-05-015", "Đặt tên", "easy", [23],
      "Đặt bí danh bảng trong FROM dùng?",
      {"A": "FROM NHANVIEN AS NV (hoặc NHANVIEN NV)",
       "B": "FROM NHANVIEN RENAME ONLY",
       "C": "FROM ALIAS NHANVIEN",
       "D": "FROM NHANVIEN :: NV bắt buộc"},
      "A", "FROM NHANVIEN AS NV, PHONGBAN AS PB."),
    q("csdl-05-016", "So sánh chuỗi", "medium", [26],
      "Trong LIKE, ký tự % có nghĩa gì?",
      {"A": "Thay cho một đoạn ký tự tùy ý",
       "B": "Thay đúng một ký tự",
       "C": "Thoát ký tự đặc biệt",
       "D": "So sánh số"},
      "A", "% = đoạn tùy ý; _ = một ký tự; ESCAPE để loại bỏ ý nghĩa đặc biệt."),
    q("csdl-05-017", "DISTINCT", "easy", [27],
      "Tại sao cần SELECT DISTINCT trong SQL?",
      {"A": "SQL không tự động loại bộ trùng như phép chiếu đại số quan hệ",
       "B": "SQL luôn loại trùng mặc định",
       "C": "DISTINCT xóa bảng",
       "D": "DISTINCT chỉ dùng với DELETE"},
      "A", "SQL có thể chứa bộ trùng; DISTINCT để khử trùng."),
    q("csdl-05-018", "Hàm tập hợp", "easy", [28],
      "Hàm COUNT(*) dùng để?",
      {"A": "Đếm số dòng của bảng/nhóm",
       "B": "Tính trung bình",
       "C": "Tìm max",
       "D": "Tính tổng lương bắt buộc"},
      "A", "COUNT(*) đếm dòng; COUNT(tt) đếm giá trị khác null."),
    q("csdl-05-019", "GROUP BY", "medium", [29],
      "Nhận xét nào đúng về WHERE và GROUP BY?",
      {"A": "WHERE thực hiện trước GROUP BY; HAVING chỉ xuất hiện khi có GROUP BY",
       "B": "HAVING luôn trước WHERE",
       "C": "GROUP BY xóa WHERE",
       "D": "HAVING không cần GROUP BY"},
      "A", "WHERE trước GROUP BY; HAVING đi với GROUP BY."),
    q("csdl-05-020", "HAVING", "medium", [31],
      "Lọc các dự án có nhiều hơn 2 nhân viên tham gia sau khi gom nhóm dùng?",
      {"A": "HAVING COUNT(*) > 2",
       "B": "WHERE COUNT(*) > 2 (trước khi join, không gom nhóm)",
       "C": "ORDER BY COUNT(*) > 2",
       "D": "DISTINCT COUNT(*) > 2"},
      "A", "Điều kiện trên nhóm → HAVING."),
    q("csdl-05-021", "ORDER BY", "easy", [33],
      "ORDER BY MaNV, MaDA DESC nghĩa là?",
      {"A": "Sắp tăng dần MaNV (mặc định ASC), trong đó MaDA giảm dần",
       "B": "Cả hai giảm dần bắt buộc",
       "C": "Cả hai tăng dần",
       "D": "Không sắp xếp"},
      "A", "Mặc định ASC; có thể chỉ định ASC/DESC từng cột."),
    q("csdl-05-022", "NULL", "medium", [35],
      "Để tìm nhân viên không có người giám sát (MaNQL null) dùng?",
      {"A": "WHERE MaNQL IS NULL",
       "B": "WHERE MaNQL = NULL",
       "C": "WHERE MaNQL == None",
       "D": "WHERE MaNQL EMPTY"},
      "A", "So sánh null bằng IS NULL / IS NOT NULL; = NULL không đúng ngữ nghĩa SQL."),
    q("csdl-05-023", "Logic 3 chân trị", "hard", [36],
      "Trong logic 3 chân trị SQL, TRUE AND UNKNOWN cho kết quả?",
      {"A": "UNKNOWN",
       "B": "TRUE",
       "C": "FALSE",
       "D": "NULL bị cấm"},
      "A", "TRUE ∧ UNKNOWN = UNKNOWN; FALSE ∧ anything = FALSE; TRUE ∨ anything = TRUE..."),
    q("csdl-05-024", "Truy vấn lồng", "medium", [37],
      "Truy vấn lồng thường xuất hiện trong mệnh đề nào theo bài giảng?",
      {"A": "WHERE (so sánh tập hợp với truy vấn con)",
       "B": "Chỉ ORDER BY",
       "C": "Chỉ CREATE TABLE",
       "D": "Chỉ DROP"},
      "A", "Truy vấn con trong WHERE với IN, ALL, ANY, EXISTS..."),
    q("csdl-05-025", "IN / ALL / EXISTS", "medium", [38],
      "EXISTS dùng để?",
      {"A": "Kiểm tra sự tồn tại kết quả của truy vấn con",
       "B": "Tính trung bình",
       "C": "Đổi tên cột",
       "D": "Tạo domain"},
      "A", "EXISTS <truy vấn con>; IN kiểm tra thuộc tập; ALL/ANY so sánh với tập."),
    q("csdl-05-026", "Truy vấn lồng phân cấp", "medium", [41],
      "Truy vấn lồng phân cấp có đặc điểm?",
      {"A": "Truy vấn con không tham chiếu thuộc tính của truy vấn cha; thực hiện con trước",
       "B": "Con luôn tham chiếu cha và chạy theo từng bộ cha",
       "C": "Không có truy vấn con",
       "D": "Chỉ dùng JOIN"},
      "A", "Phân cấp: con độc lập cha, chạy trước; tương quan: con tham chiếu cha, chạy nhiều lần."),
    q("csdl-05-027", "Truy vấn lồng tương quan", "hard", [43],
      "Tìm nhân viên không có thân nhân thường dùng mẫu nào?",
      {"A": "NOT EXISTS (SELECT * FROM THANNHAN TN WHERE TN.MaNV = NV.MaNV)",
       "B": "WHERE MaNV = ALL THANNHAN",
       "C": "HAVING THANNHAN = 0 không join",
       "D": "ORDER BY THANNHAN"},
      "A", "Lồng tương quan với NOT EXISTS."),
    q("csdl-05-028", "JOIN SQL", "easy", [47],
      "INNER JOIN hai bảng dùng cú pháp?",
      {"A": "FROM (bảng1 JOIN bảng2 ON điều kiện kết)",
       "B": "FROM bảng1 OUTER ONLY bảng2",
       "C": "FROM bảng1 DIVIDE bảng2",
       "D": "FROM bảng1 UNION bảng2 ON"},
      "A", "JOIN/INNER JOIN ... ON <đkk>; còn LEFT/RIGHT/FULL OUTER JOIN."),
    q("csdl-05-029", "BETWEEN", "easy", [25],
      "Luong BETWEEN 30000 AND 40000 tương đương?",
      {"A": "Luong >= 30000 AND Luong <= 40000",
       "B": "Luong > 30000 AND Luong < 40000 chỉ",
       "C": "Luong = 30000 OR Luong = 40000",
       "D": "Luong != 30000"},
      "A", "BETWEEN a AND b ↔ >= a và <= b."),
    q("csdl-05-030", "Hàm tập hợp vị trí", "medium", [28],
      "Hàm tập hợp chỉ được xuất hiện trong mệnh đề nào?",
      {"A": "SELECT hoặc HAVING",
       "B": "FROM",
       "C": "CREATE",
       "D": "DROP"},
      "A", "Aggregate chỉ trong SELECT hoặc HAVING."),
    q("csdl-05-031", "ON DELETE/UPDATE", "hard", [10],
      "Trong ví dụ FK TrPhong references NHANVIEN, mệnh đề ON DELETE SET NULL ON UPDATE CASCADE nghĩa là?",
      {"A": "Xóa NV được tham chiếu → đặt FK null; cập nhật MaNV → cascade sang FK",
       "B": "Xóa NV → xóa cả database",
       "C": "Không làm gì khi xóa/cập nhật",
       "D": "Chỉ chặn SELECT"},
      "A", "ON DELETE SET NULL; ON UPDATE CASCADE như trong ví dụ PHONGBAN."),
    q("csdl-05-032", "CREATE DOMAIN", "easy", [14],
      "CREATE DOMAIN Diachi AS VARCHAR(100) dùng để?",
      {"A": "Tạo miền/kiểu người dùng mới dựa trên kiểu cơ bản",
       "B": "Tạo bảng mới",
       "C": "Xóa CSDL",
       "D": "Chèn dữ liệu"},
      "A", "CREATE DOMAIN ... AS <kiểu cơ bản>."),
    q("csdl-05-033", "Kết quả SELECT", "medium", [19, 27],
      "Khác biệt quan trọng giữa bảng kết quả SQL và quan hệ toán học là?",
      {"A": "Bảng SQL có thể chứa các bộ trùng nhau",
       "B": "SQL cấm tuyệt đối trùng",
       "C": "SQL không có cột",
       "D": "SQL không có dòng"},
      "A", "Kết quả SELECT là bảng; có thể có bộ trùng (khác quan hệ toán học)."),
    q("csdl-05-034", "ALL", "hard", [40],
      "Luong > ALL (SELECT Luong FROM NHANVIEN WHERE MaPB = 5) nghĩa là?",
      {"A": "Lương lớn hơn mọi mức lương của nhân viên phòng 5",
       "B": "Lương lớn hơn ít nhất một NV phòng 5",
       "C": "Lương bằng trung bình phòng 5",
       "D": "Lương null"},
      "A", "> ALL: lớn hơn tất cả giá trị trong tập con."),
]

# ═══════════════════════════════════════════════════════════════════════════
# L06 — Ràng buộc toàn vẹn
# ═══════════════════════════════════════════════════════════════════════════
L06 = [
    q("csdl-06-001", "Giới thiệu RBTV", "easy", [3],
      "Ràng buộc toàn vẹn là gì?",
      {"A": "Các điều kiện mọi trạng thái quan hệ phải thỏa ở bất kỳ thời điểm nào",
       "B": "Chỉ tên cột",
       "C": "Chỉ giao diện người dùng",
       "D": "Một loại index"},
      "A", "RBTV: điều kiện trạng thái phải thỏa; xuất phát từ quy tắc quản lý thế giới thực."),
    q("csdl-06-002", "Mục đích RBTV", "easy", [3],
      "Mục đích của RBTV gồm?",
      {"A": "Đảm bảo tính nhất quán dữ liệu và ngữ nghĩa thực tế của CSDL",
       "B": "Chỉ tăng tốc SELECT",
       "C": "Chỉ định dạng in ấn",
       "D": "Loại bỏ khóa chính"},
      "A", "Nhất quán (ví dụ giám sát phải là NV) và ngữ nghĩa (ngày nhận chức > ngày sinh...)."),
    q("csdl-06-003", "Ba yếu tố RBTV", "easy", [3],
      "RBTV có 3 yếu tố nào?",
      {"A": "Nội dung, bối cảnh, bảng tầm ảnh hưởng",
       "B": "Chỉ nội dung",
       "C": "Chỉ SQL và index",
       "D": "Chỉ trigger và view"},
      "A", "Nội dung – bối cảnh – bảng tầm ảnh hưởng."),
    q("csdl-06-004", "Nội dung RBTV", "medium", [4],
      "Nội dung RBTV có thể phát biểu bằng?",
      {"A": "Ngôn ngữ tự nhiên hoặc ngôn ngữ hình thức (đại số/phép tính quan hệ, mã giả)",
       "B": "Chỉ hình ảnh",
       "C": "Chỉ màu sắc UI",
       "D": "Chỉ tên server"},
      "A", "Tự nhiên (dễ hiểu) hoặc hình thức (toán học)."),
    q("csdl-06-005", "Bối cảnh", "easy", [6],
      "Bối cảnh của RBTV là gì?",
      {"A": "Những quan hệ mà RBTV có hiệu lực (một hoặc nhiều quan hệ)",
       "B": "Chỉ thời gian chạy query",
       "C": "Chỉ quyền DBA",
       "D": "Tên miền mạng"},
      "A", "Bối cảnh = quan hệ chịu hiệu lực RBTV."),
    q("csdl-06-006", "Bảng tầm ảnh hưởng", "medium", [7],
      "Bảng tầm ảnh hưởng dùng để?",
      {"A": "Xác định thời điểm cần kiểm tra RBTV khi thêm/xóa/sửa trên bối cảnh",
       "B": "Vẽ ER",
       "C": "Tính lương",
       "D": "Sao lưu"},
      "A", "Xác định thao tác nào (+/−) cần kiểm tra RBTV."),
    q("csdl-06-007", "Bảng tầm ảnh hưởng", "medium", [8],
      "Với RBTV “mỗi NV có mã riêng” (khóa), thao tác nào trên NHANVIEN cần kiểm tra?",
      {"A": "Thêm (và thường khi sửa mã); xóa không ảnh hưởng tính duy nhất còn lại theo bảng ví dụ",
       "B": "Chỉ xóa",
       "C": "Không bao giờ",
       "D": "Chỉ SELECT"},
      "A", "Ví dụ RB-1: Thêm +, Xóa −, Sửa − (trên MaNV theo bảng bài giảng)."),
    q("csdl-06-008", "Phân loại RBTV", "easy", [11],
      "RBTV có bối cảnh một quan hệ gồm các loại?",
      {"A": "Miền giá trị, liên thuộc tính, liên bộ",
       "B": "Chỉ tham chiếu",
       "C": "Chỉ thuộc tính tổng hợp",
       "D": "Chỉ liên quan hệ"},
      "A", "Một quan hệ: miền giá trị, liên thuộc tính, liên bộ."),
    q("csdl-06-009", "Phân loại RBTV", "easy", [11],
      "RBTV có bối cảnh nhiều quan hệ gồm?",
      {"A": "Tham chiếu; liên thuộc tính–liên quan hệ; liên bộ–liên quan hệ; thuộc tính tổng hợp",
       "B": "Chỉ miền giá trị",
       "C": "Chỉ liên bộ trong một bảng",
       "D": "Chỉ DEFAULT"},
      "A", "Nhiều quan hệ: tham chiếu, liên tt-liên QH, liên bộ-liên QH, thuộc tính tổng hợp."),
    q("csdl-06-010", "RBTV miền giá trị", "easy", [12],
      "“Lương nhân viên không thấp hơn 10.000” là RBTV loại nào?",
      {"A": "RBTV miền giá trị",
       "B": "RBTV tham chiếu",
       "C": "RBTV thuộc tính tổng hợp",
       "D": "Liên kết M:N"},
      "A", "Ràng buộc trên miền/giá trị thuộc tính (CHECK domain)."),
    q("csdl-06-011", "RBTV liên thuộc tính", "medium", [14],
      "“Ngày xếp lương > ngày sinh” trên cùng bộ NHANVIEN là?",
      {"A": "RBTV liên thuộc tính",
       "B": "RBTV tham chiếu liên quan hệ",
       "C": "RBTV thuộc tính tổng hợp",
       "D": "Outer join"},
      "A", "Liên thuộc tính: quan hệ giữa các thuộc tính trong cùng bộ/quan hệ."),
    q("csdl-06-012", "RBTV liên thuộc tính", "medium", [14],
      "“Nhân viên không được giám sát chính mình” (MaGSat ≠ MaNV) là?",
      {"A": "RBTV liên thuộc tính",
       "B": "RBTV miền giá trị thuần túy không liên thuộc tính",
       "C": "Phép chia",
       "D": "Natural join"},
      "A", "RB-8: liên thuộc tính trên cùng bộ."),
    q("csdl-06-013", "RBTV liên bộ", "medium", [15],
      "RBTV liên bộ nói về?",
      {"A": "Sự tồn tại/phụ thuộc giữa các bộ; trường hợp đặc biệt là ràng buộc khóa chính",
       "B": "Chỉ kiểu dữ liệu cột",
       "C": "Chỉ font chữ",
       "D": "Chỉ tên schema"},
      "A", "Liên bộ: bộ này phụ thuộc bộ khác; PK là trường hợp đặc biệt."),
    q("csdl-06-014", "RBTV tham chiếu", "easy", [16],
      "“Chỉ NV công ty mới tham gia dự án công ty” (THAMGIA phụ thuộc NHANVIEN và DUAN) là?",
      {"A": "RBTV tham chiếu",
       "B": "RBTV miền giá trị đơn",
       "C": "Phép hội",
       "D": "View"},
      "A", "Tồn tại bộ THAMGIA phụ thuộc tồn tại NV và DA tương ứng."),
    q("csdl-06-015", "RBTV tham chiếu", "hard", [18],
      "RBTV “người giám sát (nếu có) phải là một nhân viên” cho thấy?",
      {"A": "RBTV tham chiếu có thể có bối cảnh là một quan hệ (tự tham chiếu)",
       "B": "Tham chiếu luôn cần ≥ 3 quan hệ",
       "C": "Không thể tự tham chiếu",
       "D": "Chỉ dùng UNION"},
      "A", "RB-11: tham chiếu trong cùng NHANVIEN."),
    q("csdl-06-016", "RBTV liên tt – liên QH", "medium", [19],
      "“Ngày nhận chức trưởng phòng > ngày sinh NV trưởng phòng” là?",
      {"A": "RBTV liên thuộc tính – liên quan hệ",
       "B": "RBTV miền giá trị một cột đơn không liên quan hệ",
       "C": "Chỉ PRIMARY KEY",
       "D": "Chỉ INDEX"},
      "A", "RB-12: thuộc tính trên PHONGBAN và NHANVIEN."),
    q("csdl-06-017", "RBTV liên bộ – liên QH", "medium", [20],
      "“Lương NV không cao hơn lương trưởng phòng” là?",
      {"A": "RBTV liên bộ – liên quan hệ",
       "B": "RBTV miền giá trị tĩnh một hằng",
       "C": "Chỉ UNIQUE",
       "D": "Chỉ DOMAIN"},
      "A", "RB-13: so sánh bộ NV với bộ trưởng phòng qua PHONGBAN."),
    q("csdl-06-018", "RBTV thuộc tính tổng hợp", "medium", [21],
      "“TongLuong phòng = tổng lương các NV phòng đó” là?",
      {"A": "RBTV thuộc tính tổng hợp",
       "B": "RBTV khóa chính",
       "C": "Phép chiếu",
       "D": "Đổi tên"},
      "A", "Thuộc tính tính từ thuộc tính/bộ quan hệ khác."),
    q("csdl-06-019", "Cài đặt RBTV", "easy", [22],
      "Các cơ chế cài đặt RBTV theo bài giảng gồm?",
      {"A": "Primary key, Foreign key, Check, Assertion, Trigger, Stored Procedure",
       "B": "Chỉ SELECT và ORDER BY",
       "C": "Chỉ GUI validation",
       "D": "Chỉ file CSV"},
      "A", "PK, FK, CHECK, ASSERTION, TRIGGER, STORED PROCEDURE."),
    q("csdl-06-020", "Assertion", "medium", [23],
      "Assertion trong SQL dùng để?",
      {"A": "Phát biểu điều kiện toàn vẹn (thường liên quan nhiều bảng) bằng CREATE ASSERTION ... CHECK",
       "B": "Tạo index",
       "C": "Xóa database",
       "D": "Chỉ đổi tên cột"},
      "A", "create assertion <tên> check <điều kiện>."),
    q("csdl-06-021", "Trigger", "medium", [25],
      "Mô hình ECA của trigger gồm?",
      {"A": "Sự kiện – Điều kiện – Hành động",
       "B": "Chỉ sự kiện",
       "C": "Entity – Column – Attribute",
       "D": "Export – Copy – Archive"},
      "A", "ECA: Event–Condition–Action."),
    q("csdl-06-022", "Trigger", "medium", [26],
      "Trigger có thể kích hoạt AFTER/BEFORE trên sự kiện nào?",
      {"A": "INSERT, DELETE, UPDATE",
       "B": "Chỉ SELECT",
       "C": "Chỉ CREATE TABLE",
       "D": "Chỉ GRANT"},
      "A", "after|before insert|delete|update on <bảng>."),
    q("csdl-06-023", "Stored Procedure", "easy", [28],
      "Stored Procedure là gì?",
      {"A": "Thủ tục/hàm lưu trong lược đồ CSDL, gọi được từ SQL",
       "B": "Một loại khóa ngoại",
       "C": "Một view chỉ đọc bắt buộc",
       "D": "Một domain"},
      "A", "Procedure lưu trong schema; exec <tên> <tham số>."),
    q("csdl-06-024", "Ví dụ RB", "medium", [5],
      "“Mỗi nhân viên chỉ tham gia không quá 3 dự án” thuộc nhóm nào gần nhất?",
      {"A": "RBTV liên bộ (trên THAMGIA)",
       "B": "RBTV miền giá trị một hằng lương",
       "C": "Chỉ PRIMARY KEY MaNV",
       "D": "Natural join"},
      "A", "RB-3: card tham gia theo MaNV ≤ 3 — liên bộ."),
    q("csdl-06-025", "Ví dụ RB", "medium", [5],
      "“Mỗi phòng ban phải có ít nhất một nhân viên” là?",
      {"A": "RBTV liên bộ – liên quan hệ (tồn tại NV thuộc phòng)",
       "B": "RBTV miền giá trị TenPB",
       "C": "Chỉ UNIQUE TenPB",
       "D": "Phép chia"},
      "A", "RB-4: ∀ phòng ∃ NV thuộc phòng."),
    q("csdl-06-026", "Tầm ảnh hưởng tham chiếu", "hard", [16],
      "Với RBTV tham chiếu THAMGIA → NHANVIEN/DUAN, khi nào cần kiểm tra trên NHANVIEN?",
      {"A": "Khi xóa (và có thể sửa khóa) nhân viên được tham chiếu",
       "B": "Chỉ khi SELECT",
       "C": "Không bao giờ",
       "D": "Chỉ khi tạo DOMAIN"},
      "A", "Bảng RB-9: NHANVIEN Xóa +; THAMGIA Thêm +."),
    q("csdl-06-027", "Assertion ví dụ", "hard", [23, 24],
      "Assertion kiểm tra “không tồn tại phòng có ngày nhận chức < ngày sinh trưởng phòng” thường dùng kỹ thuật?",
      {"A": "CHECK (NOT EXISTS (SELECT ... WHERE điều kiện vi phạm))",
       "B": "ORDER BY NgSinh",
       "C": "DISTINCT TrPhong",
       "D": "UNION ALL"},
      "A", "Ví dụ RB_12: not exists select ... NgSinh > NgNhanChuc."),
    q("csdl-06-028", "Trigger ví dụ", "hard", [27],
      "Trigger chặn lương NV cao hơn lương giám sát thường đặt?",
      {"A": "BEFORE INSERT OR UPDATE OF Luong ... WHEN (new.Luong > ... ) báo lỗi",
       "B": "AFTER SELECT",
       "C": "BEFORE DROP DATABASE",
       "D": "ONLY ON COMMIT DDL"},
      "A", "Ví dụ RB_13: before insert/update of Luong, so sánh new.Luong với lương giám sát."),
    q("csdl-06-029", "Phân loại mục đích", "easy", [11],
      "Mục đích phân loại RBTV theo bối cảnh là?",
      {"A": "Giúp người thiết kế phát hiện các RBTV của một CSDL",
       "B": "Chỉ để trang trí tài liệu",
       "C": "Thay thế ER",
       "D": "Xóa dữ liệu định kỳ"},
      "A", "Phân loại giúp phát hiện RBTV khi thiết kế."),
    q("csdl-06-030", "Miền giá trị động", "hard", [13],
      "RBTV “khi lương đổi thì ngày xếp lương phải tăng” mang tính?",
      {"A": "Ràng buộc trên sự chuyển trạng thái (trước/sau cập nhật)",
       "B": "Chỉ UNIQUE tĩnh",
       "C": "Chỉ FOREIGN KEY tĩnh",
       "D": "Không phải RBTV"},
      "A", "RB-6: so sánh bộ trước và sau cập nhật (τ)."),
]

# ═══════════════════════════════════════════════════════════════════════════
# L07 — Phụ thuộc hàm và chuẩn hóa
# ═══════════════════════════════════════════════════════════════════════════
L07 = [
    q("csdl-07-001", "Nguyên tắc thiết kế", "easy", [3],
      "Các tiêu chí đánh giá chất lượng thiết kế quan hệ gồm?",
      {"A": "Ngữ nghĩa thuộc tính rõ; giảm thừa; giảm null; không phát sinh bộ không có thực",
       "B": "Chỉ số lượng bảng càng nhiều càng tốt",
       "C": "Chỉ dùng một bảng duy nhất luôn luôn",
       "D": "Bỏ hết khóa"},
      "A", "Ngữ nghĩa, giảm thừa, giảm null, tránh bộ giả khi join."),
    q("csdl-07-002", "Ngữ nghĩa thuộc tính", "medium", [5],
      "Vì sao nên tránh gộp thuộc tính nhiều kiểu thực thể vào một lược đồ?",
      {"A": "Làm ngữ nghĩa khó hiểu và dễ gây trùng lặp/dị thường",
       "B": "Vì SQL không cho phép nhiều cột",
       "C": "Vì khóa ngoại bị cấm",
       "D": "Vì không có JOIN"},
      "A", "Ý nghĩa thuộc tính càng rõ càng tốt; tránh tổ hợp thuộc tính nhiều thực thể."),
    q("csdl-07-003", "Dị thường cập nhật", "medium", [7, 8],
      "Thông tin thừa trong bộ có thể gây ra?",
      {"A": "Dị thường thêm, xóa, sửa",
       "B": "Chỉ tăng tốc query",
       "C": "Loại bỏ null",
       "D": "Tự động BCNF"},
      "A", "Redundancy → insertion/deletion/update anomalies."),
    q("csdl-07-004", "Null", "easy", [9],
      "Nhiều giá trị null gây khó khăn gì?",
      {"A": "Lãng phí không gian; khó phép kết; khó hàm tập hợp",
       "B": "Tự động chuẩn hóa",
       "C": "Tăng tính nhất quán",
       "D": "Thay thế khóa chính"},
      "A", "Tránh thuộc tính nhận nhiều null."),
    q("csdl-07-005", "Bộ không có thực", "hard", [10, 12],
      "Để tránh phát sinh bộ không có thực khi join, nên?",
      {"A": "Thiết kế sao cho join bằng chủ yếu trên khóa chính/khóa ngoại",
       "B": "Join tự do mọi cột văn bản",
       "C": "Bỏ hết khóa",
       "D": "Gộp mọi quan hệ thành một"},
      "A", "Join trên PK/FK để tránh dangling/spurious tuples."),
    q("csdl-07-006", "Phụ thuộc hàm", "easy", [14],
      "X → Y đúng khi nào?",
      {"A": "Mọi cặp bộ trùng trên X thì phải trùng trên Y",
       "B": "Mọi cặp bộ trùng trên Y thì trùng trên X",
       "C": "X và Y rời nhau luôn",
       "D": "X là null"},
      "A", "∀ t1,t2: t1[X]=t2[X] ⇒ t1[Y]=t2[Y]."),
    q("csdl-07-007", "Phụ thuộc hàm", "medium", [14],
      "Cho quan hệ có (A,B) = (1,4) và (1,5). Kết luận nào đúng?",
      {"A": "Không thỏa A → B; có thể thỏa B → A",
       "B": "Thỏa A → B",
       "C": "Không có PTH nào",
       "D": "Bắt buộc A → B và B → A"},
      "A", "Cùng A khác B ⇒ không A→B; các B khác nhau có thể xác định A."),
    q("csdl-07-008", "PTH và khóa", "medium", [15],
      "Nếu K là khóa của R thì?",
      {"A": "K xác định hàm tất cả các tập thuộc tính của R",
       "B": "K không xác định gì",
       "C": "K chỉ xác định một thuộc tính",
       "D": "K phải null"},
      "A", "Khóa xác định hàm mọi thuộc tính; PTH phản ánh ràng buộc thế giới thực."),
    q("csdl-07-009", "Bao đóng F+", "easy", [16],
      "Bao đóng F+ của tập PTH F gồm?",
      {"A": "F và mọi PTH suy diễn được từ F",
       "B": "Chỉ F",
       "C": "Chỉ PTH không thuộc F",
       "D": "Tập rỗng"},
      "A", "F+ = F ∪ các PTH suy diễn từ F; F đầy đủ nếu F=F+."),
    q("csdl-07-010", "Luật Armstrong", "medium", [17],
      "Ba luật Armstrong cơ bản là?",
      {"A": "Phản xạ, tăng trưởng, bắc cầu",
       "B": "Chỉ phân rã",
       "C": "Chỉ hợp",
       "D": "Chỉ hiệu"},
      "A", "Reflexivity, Augmentation, Transitivity — hệ đầy đủ."),
    q("csdl-07-011", "Luật suy diễn", "medium", [17],
      "Từ X → YZ suy ra X → Y và X → Z nhờ luật nào?",
      {"A": "Phân rã",
       "B": "Tăng trưởng",
       "C": "Phản xạ ngược",
       "D": "Cartesian"},
      "A", "Decomposition: X→YZ ⇒ X→Y, X→Z."),
    q("csdl-07-012", "Bao đóng thuộc tính", "medium", [18],
      "X → Y ∈ F+ khi và chỉ khi?",
      {"A": "Y ⊆ X+",
       "B": "X ⊆ Y+",
       "C": "X ∩ Y = ∅",
       "D": "X = U"},
      "A", "X→Y suy được ⇔ Y ⊆ X+; nếu K khóa thì K+=U."),
    q("csdl-07-013", "Tính X+", "medium", [19, 20],
      "Cho F={AB→C, BC→D, D→EG}, X=BD. X+ bằng?",
      {"A": "BDEG",
       "B": "BD",
       "C": "ABCDEG",
       "D": "EG"},
      "A", "BD; D→EG ⇒ BDEG; không thêm được nữa."),
    q("csdl-07-014", "Tập PTH tương đương", "medium", [22],
      "F và G tương đương khi nào?",
      {"A": "F phủ G và G phủ F (tức F+=G+)",
       "B": "F ⊂ G nghiêm ngặt",
       "C": "F ∩ G = ∅",
       "D": "Chỉ cùng số PTH"},
      "A", "Tương đương ⇔ F+=G+."),
    q("csdl-07-015", "Phủ tối thiểu", "hard", [24],
      "Tập PTH tối thiểu cần thỏa?",
      {"A": "Vế phải 1 thuộc tính; không thừa thuộc tính vế trái; không thừa PTH",
       "B": "Càng nhiều PTH càng tốt",
       "C": "Mọi PTH có vế phải toàn U",
       "D": "Không có phản xạ"},
      "A", "3 điều kiện phủ tối thiểu."),
    q("csdl-07-016", "Phủ tối thiểu ví dụ", "hard", [26],
      "Phủ tối thiểu của E={A→BC, A→B, B→C, AB→C} theo ví dụ bài giảng là?",
      {"A": "{A→B, B→C}",
       "B": "{A→BC, AB→C}",
       "C": "{AB→C}",
       "D": "{A→C}"},
      "A", "Sau tách, loại thừa trái, loại A→C thừa → {A→B,B→C}."),
    q("csdl-07-017", "Siêu khóa/khóa qua PTH", "medium", [27],
      "S là siêu khóa nếu?",
      {"A": "S xác định hàm mọi thuộc tính (S+ = U) — các bộ khác nhau khác trên S",
       "B": "S chỉ có một thuộc tính luôn",
       "C": "S = ∅",
       "D": "S chỉ ở vế phải"},
      "A", "Siêu khóa: t1≠t2 ⇒ t1[S]≠t2[S]; khóa = siêu khóa nhỏ nhất."),
    q("csdl-07-018", "Tìm khóa", "hard", [29],
      "Cho U={A..G}, F={B→A, D→C, D→BE, DF→G}. Khóa theo ví dụ là?",
      {"A": "DF",
       "B": "D",
       "C": "B",
       "D": "ABCDEFG"},
      "A", "Thuật toán loại thuộc tính dần → K=DF."),
    q("csdl-07-019", "1NF", "easy", [35],
      "Dạng chuẩn 1 yêu cầu gì?",
      {"A": "Mọi thuộc tính là thuộc tính đơn (nguyên tử)",
       "B": "Mọi PTH đều có vế trái siêu khóa",
       "C": "Không có khóa",
       "D": "Chỉ có một bộ"},
      "A", "1NF: thuộc tính đơn; ví dụ bung danh sách trụ sở."),
    q("csdl-07-020", "1NF", "medium", [36],
      "Nhận xét nào đúng về 1NF?",
      {"A": "Mọi lược đồ quan hệ (theo định nghĩa quan hệ) thuộc 1NF; vẫn có thể trùng lặp/dị thường",
       "B": "1NF loại bỏ mọi dị thường",
       "C": "1NF = BCNF",
       "D": "1NF cấm khóa chính"},
      "A", "1NF vẫn có thể dư thừa và dị thường cập nhật."),
    q("csdl-07-021", "2NF", "medium", [37],
      "2NF (theo khóa chính) yêu cầu?",
      {"A": "Mọi thuộc tính không khóa phụ thuộc đầy đủ vào khóa chính",
       "B": "Mọi thuộc tính đa trị",
       "C": "Không có khóa chính",
       "D": "Chỉ có PTH bắt cầu"},
      "A", "Không còn PTH bộ phận từ khóa chính tới thuộc tính không khóa."),
    q("csdl-07-022", "PTH đầy đủ/bộ phận", "medium", [37],
      "PTH X→Y là đầy đủ khi?",
      {"A": "Không có thuộc tính nào của X có thể bỏ mà vẫn suy ra Y",
       "B": "X có đúng một thuộc tính luôn",
       "C": "Y chứa X",
       "D": "X = U"},
      "A", "∀A∈X, (X−{A})→Y không đúng ⇒ đầy đủ; ngược lại là bộ phận."),
    q("csdl-07-023", "2NF nhận xét", "medium", [39],
      "Nếu R chỉ có một khóa và khóa có đúng 1 thuộc tính thì?",
      {"A": "R thuộc 2NF",
       "B": "R không thể 1NF",
       "C": "R luôn BCNF",
       "D": "R không có PTH"},
      "A", "card(K)=1 ⇒ không PTH bộ phận từ khóa → 2NF."),
    q("csdl-07-024", "3NF", "medium", [40],
      "3NF (theo khóa chính) yêu cầu thêm so với 2NF?",
      {"A": "Không còn phụ thuộc bắt cầu của thuộc tính không khóa vào khóa chính",
       "B": "Cho phép mọi PTH bộ phận",
       "C": "Cấm khóa ngoại",
       "D": "Cấm 1NF"},
      "A", "2NF + không PTH bắt cầu tới thuộc tính không khóa."),
    q("csdl-07-025", "3NF", "medium", [41],
      "Nhận xét nào đúng?",
      {"A": "3NF ⇒ 2NF; PTH bắt cầu gây trùng lặp; 3NF là mức tối thiểu thường nhắm tới khi thiết kế",
       "B": "2NF ⇒ 3NF luôn",
       "C": "3NF cấm mọi khóa",
       "D": "3NF = chỉ 1NF"},
      "A", "3NF ⊂ 2NF về mặt chặt; mục tiêu tối thiểu thường là 3NF."),
    q("csdl-07-026", "3NF tổng quát", "hard", [43],
      "Định nghĩa 3NF tổng quát: với PTH không hiển nhiên X→A thì?",
      {"A": "X là siêu khóa hoặc A là thuộc tính khóa",
       "B": "X phải là khóa duy nhất và A không khóa",
       "C": "A phải là siêu khóa",
       "D": "X phải null"},
      "A", "X superkey OR A prime attribute."),
    q("csdl-07-027", "BCNF", "hard", [44],
      "BCNF yêu cầu gì với mọi PTH không hiển nhiên X→Y?",
      {"A": "X là siêu khóa",
       "B": "Y là siêu khóa",
       "C": "X là thuộc tính không khóa",
       "D": "Y chứa X"},
      "A", "BCNF: mọi PTH không tầm thường có vế trái là superkey; chặt hơn 3NF."),
    q("csdl-07-028", "BCNF vs 3NF", "medium", [46],
      "Nhận xét đúng về BCNF và 3NF?",
      {"A": "BCNF ⇒ 3NF; BCNF đơn giản/chặt hơn; mục tiêu chuẩn hóa thường về 3NF hoặc BCNF",
       "B": "3NF ⇒ BCNF luôn",
       "C": "BCNF lỏng hơn 1NF",
       "D": "BCNF cấm quan hệ"},
      "A", "BCNF mạnh hơn 3NF; có lược đồ 3NF nhưng không BCNF."),
    q("csdl-07-029", "Thiết kế top-down", "easy", [47],
      "Các bước thiết kế top-down gồm?",
      {"A": "EER khái niệm → quan hệ → xác định PTH → chuẩn hóa loại PTH bộ phận/bắt cầu",
       "B": "Chỉ viết SQL không thiết kế",
       "C": "Chỉ tạo trigger",
       "D": "Chỉ backup"},
      "A", "Khái niệm EER → quan hệ → F → chuẩn hóa."),
    q("csdl-07-030", "Phân rã", "medium", [49],
      "Yêu cầu khi phân rã lược đồ gồm?",
      {"A": "Bảo toàn thuộc tính; các Ri ở 3NF hoặc BCNF",
       "B": "Mất hết thuộc tính",
       "C": "Chỉ một Ri rỗng",
       "D": "Bỏ F"},
      "A", "Bảo toàn thuộc tính; chuẩn 3NF/BCNF."),
    q("csdl-07-031", "Bảo toàn PTH", "hard", [50],
      "Phân rã bảo toàn PTH nghĩa là?",
      {"A": "(∪ π_Ri(F))+ = F+",
       "B": "Chỉ |D|=1",
       "C": "Mọi Ri rỗng",
       "D": "F = ∅"},
      "A", "Hợp các chiếu PTH lên các Ri bao đóng lại bằng F+."),
    q("csdl-07-032", "Định lý 7.1", "medium", [52],
      "Định lý 7.1 khẳng định?",
      {"A": "Tồn tại phân rã bảo toàn PTH về các lược đồ 3NF",
       "B": "Không tồn tại phân rã 3NF",
       "C": "Mọi phân rã đều mất PTH",
       "D": "Chỉ BCNF bảo toàn PTH luôn"},
      "A", "Luôn có phân rã 3NF bảo toàn PTH (Thuật toán 7.4 từ phủ tối thiểu)."),
    q("csdl-07-033", "Không mất thông tin", "hard", [56],
      "Phân rã 2 thành phần {R1,R2} không mất thông tin đối với F khi?",
      {"A": "(U1∩U2)→(U1−U2) ∈ F+ hoặc (U1∩U2)→(U2−U1) ∈ F+",
       "B": "U1 ∩ U2 = ∅ luôn",
       "C": "F rỗng",
       "D": "Chỉ khi không có PTH"},
      "A", "Định lý 7.2: giao xác định hiệu một phía."),
    q("csdl-07-034", "Thuật toán BCNF", "hard", [57],
      "Khi Q vi phạm BCNF vì X→Y, thuật toán tách Q thành?",
      {"A": "Q1 = UQ − Y và Q2 = X ∪ Y",
       "B": "Q1 = Y và Q2 = Y",
       "C": "Q1 = UQ và Q2 = ∅",
       "D": "Không tách"},
      "A", "Thuật toán 7.5: UQ1=UQ−Y, UQ2=X∪Y."),
    q("csdl-07-035", "PTH bắt cầu", "medium", [40],
      "X→Y là PTH bắt cầu nếu tồn tại Z sao cho?",
      {"A": "X→Z, Z→Y và Z không phải khóa cũng không là tập con khóa",
       "B": "Z = X",
       "C": "Z = U luôn",
       "D": "Z là khóa chính"},
      "A", "Transitive FD qua Z không phải (tập con) khóa."),
    q("csdl-07-036", "Ví dụ chuẩn hóa 2NF", "medium", [38],
      "NVIEN_DUAN với khóa (MaNV,MaDA) và TenNV phụ thuộc chỉ MaNV thì?",
      {"A": "Vi phạm 2NF do PTH bộ phận; cần tách quan hệ",
       "B": "Đang BCNF chắc chắn",
       "C": "Không có vấn đề",
       "D": "Vi phạm chỉ vì null"},
      "A", "TenNV phụ thuộc bộ phận khóa → tách NV_DA2(MaNV,TenNV)..."),
]

LECTURES = [
    ("csdl-01", "L01 - Tổng quan về cơ sở dữ liệu",
     "L01-Tổng quan về cơ sở dữ liệu.pptx", L01),
    ("csdl-02", "L02 - Mô hình thực thể liên kết (ER)",
     "L02-Mô hình thực thể liên kết (ER).pptx", L02),
    ("csdl-03", "L03 - Mô hình quan hệ",
     "L03-Mô hình Quan hệ.pptx", L03),
    ("csdl-04", "L04 - Đại số quan hệ",
     "L04-Đại số quan hệ.pptx", L04),
    ("csdl-05", "L05 - Ngôn ngữ truy vấn SQL",
     "L05-Ngôn ngữ truy vấn SQL.pptx", L05),
    ("csdl-06", "L06 - Ràng buộc toàn vẹn",
     "L06-Ràng buộc toàn vẹn.pptx", L06),
    ("csdl-07", "L07 - Phụ thuộc hàm và chuẩn hóa",
     "L07-Phụ thuộc hàm và chuẩn hóa.pptx", L07),
]


def main():
    total = 0
    for chapter_id, title, source, questions in LECTURES:
        data = quiz(chapter_id, title, source, questions)
        path = OUT / f"{chapter_id}.json"
        path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
        total += len(questions)
        print(f"Wrote {path.name}: {len(questions)} questions")
    print(f"TOTAL: {total} questions in {len(LECTURES)} files")


if __name__ == "__main__":
    main()
